<?php
/**
 * Company, conversion, and insight pages.
 *
 * @package Sovassa
 */

return array(
	'home' => array(
		'layout'           => 'home',
		'wp_title'         => 'Home',
		'nav_label'        => 'Home',
		'title'            => 'A technology and marketing partner for',
		'rotate'           => array('Websites', 'Mobile products', 'Search growth', 'Automation'),
		'eyebrow'          => 'Build · Market · Grow',
		'intro'            => 'Sovassa Technologies designs and builds digital products, then markets them with the same team. The work stays tied to a business outcome instead of a pile of disconnected vendors.',
		'meta_title'       => 'Sovassa Technologies | Web, Product, and Digital Marketing',
		'meta_description' => 'Sovassa Technologies builds websites, apps, and AI products and markets them through SEO, content, and paid media. One team for build, market, and grow.',
		'trust'            => array(
			array('icon' => 'layers', 'label' => 'Technology and marketing, one team'),
			array('icon' => 'check', 'label' => 'Scoped work with a named next step'),
			array('icon' => 'globe', 'label' => 'Web, mobile, and applied AI'),
			array('icon' => 'search', 'label' => 'Search, content, and paid growth'),
		),
		'goals'            => array(
			array('title' => 'A website or web app', 'text' => 'Replace a site the team cannot edit, or ship a product people can actually use.', 'slug' => 'web-development'),
			array('title' => 'A mobile product', 'text' => 'Plan an iOS, Android, or cross-platform app around a real job to be done.', 'slug' => 'mobile-app-development'),
			array('title' => 'Qualified leads', 'text' => 'Give sales a clearer path from first visit to a conversation worth having.', 'slug' => 'solutions'),
			array('title' => 'Search visibility', 'text' => 'Make the services you sell easier to find, and easier to trust.', 'slug' => 'seo'),
			array('title' => 'Paid acquisition', 'text' => 'Run search and social campaigns that match the page a person lands on.', 'slug' => 'google-ads'),
			array('title' => 'Automation or AI', 'text' => 'Remove a repeated handoff, or add a practical AI workflow with a human check.', 'slug' => 'ai-automation'),
		),
		'why'              => array(
			array('title' => 'One thread from product to promotion', 'text' => 'The people who shape the offer also shape the site, the campaign, and the follow-up.'),
			array('title' => 'Decisions you can see', 'text' => 'Scope, milestones, and the measure of progress are written down before production starts.'),
			array('title' => 'Handover that stays usable', 'text' => 'You leave with a system your team can edit, not a file only we can open.'),
			array('title' => 'Growth after launch', 'text' => 'Reporting looks at enquiries, product use, and the next improvement, not a dashboard for its own sake.'),
		),
		'delivery'         => array(
			array('title' => 'Discover', 'text' => 'Understand the business, the audience, the current systems, and the constraint that actually matters.'),
			array('title' => 'Strategize', 'text' => 'Choose the offer, the pages or product scope, and the measure that will tell us the work is working.'),
			array('title' => 'Build', 'text' => 'Design, develop, write, or configure the approved work and review it in the open.'),
			array('title' => 'Grow', 'text' => 'Launch, support, and improve the parts that move enquiries, usage, or revenue.'),
		),
		'marketing'        => array(
			array('title' => 'Research', 'text' => 'Read the market, the current site, and the questions sales already hears.'),
			array('title' => 'Strategy', 'text' => 'Pick channels and messages that match how the company actually wins work.'),
			array('title' => 'Execute', 'text' => 'Publish, launch, and connect the work to the pages and forms that receive it.'),
			array('title' => 'Optimize', 'text' => 'Change the pieces that the numbers and the sales team both notice.'),
			array('title' => 'Report', 'text' => 'Share what changed, what did not, and the next decision in plain language.'),
		),
		'faq'              => array(
			array('q' => 'What does Sovassa Technologies do?', 'a' => 'We build websites, web apps, mobile products, and practical AI workflows, and we market them through SEO, content, social, and paid media. The point is to keep product and marketing in one plan.'),
			array('q' => 'Can we hire Sovassa for a single service?', 'a' => 'Yes. A website, a design engagement, an SEO program, or a paid media account can stand alone. We will say when a neighbouring service would change the result.'),
			array('q' => 'How does a project start?', 'a' => 'With a short consultation. We confirm the goal, the constraints, and whether we are the right team. If we are, you get a proposed scope and a way to begin.'),
			array('q' => 'Do you publish client metrics on this site?', 'a' => 'Only when they come from a completed engagement and the client is comfortable sharing them. Until then, the work page describes the kinds of problems we take on.'),
		),
	),
	'about' => array(
		'layout'           => 'about',
		'wp_title'         => 'About Us',
		'nav_label'        => 'About Us',
		'title'            => 'A company for teams that need the product and the marketing to agree.',
		'eyebrow'          => 'About Sovassa',
		'intro'            => 'Sovassa Technologies exists for companies whose website, product, and marketing were built as separate projects and no longer describe the same business.',
		'meta_title'       => 'About Us | Sovassa Technologies',
		'meta_description' => 'Sovassa Technologies is a technology and digital marketing company. We combine product building and marketing under one Build, Market, Grow model.',
		'story'            => array(
			'Sovassa is a new company, and we would rather say that plainly than invent a long history. The problem we are organised around is familiar: a business hires one team to build and another to promote, then spends the year translating between them.',
			'We bring those conversations into the same room. Strategy, design, engineering, and marketing share the offer, the audience, and the result the work is supposed to change.',
		),
		'vision'           => 'Companies should be able to explain what they do, ship the product that proves it, and reach the people who need it without starting over every quarter.',
		'mission'          => 'Help ambitious teams build useful digital products and market them with a plan that sales, marketing, and delivery can all recognise.',
		'values'           => array(
			array('title' => 'Clarity before decoration', 'text' => 'A page, a screen, or a campaign earns its place when a person can tell what to do next.'),
			array('title' => 'Honest scope', 'text' => 'We name what is included, what is not, and what we still need to learn.'),
			array('title' => 'Proof over performance', 'text' => 'We do not publish numbers we cannot stand behind. Real results will be added when they are real.'),
			array('title' => 'Systems people can keep', 'text' => 'The work should survive the project. Editing, reporting, and handover are part of the delivery.'),
		),
		'with_clients'     => array(
			array('title' => 'A named owner', 'text' => 'One person on our side keeps the thread, even when specialists join the work.'),
			array('title' => 'Shared working notes', 'text' => 'Decisions live where both teams can see them, not in a private chat.'),
			array('title' => 'Reviews with something to react to', 'text' => 'We show pages, flows, and drafts early enough to change them.'),
			array('title' => 'A finish line and a next step', 'text' => 'Launch includes what your team will do on Monday, not only a file handoff.'),
		),
		'capabilities'     => array(
			array('title' => 'Build', 'text' => 'Websites, web apps, mobile products, applied AI, and the interface design that holds them together.'),
			array('title' => 'Market', 'text' => 'SEO, content, social, and paid media aimed at the same offer the product describes.'),
			array('title' => 'Grow', 'text' => 'Measurement and packaged solutions that combine building and marketing around one result.'),
		),
		'why_choose'       => array(
			array('title' => 'One plan, not two vendors', 'text' => 'The people who shape the product also shape how it is explained and promoted.'),
			array('title' => 'Scope you can read', 'text' => 'What is included, what is not, and how progress will be judged are written down before production.'),
			array('title' => 'A handover the team can use', 'text' => 'Editing, reporting, and the next improvement are part of the delivery, not a later surprise.'),
		),
		'faq'              => array(
			array('q' => 'Where is Sovassa based?', 'a' => 'The office is in Zirakpur, India. We also work with clients remotely, and a proposal will say if a visit is useful.'),
			array('q' => 'Who will we work with?', 'a' => 'Team profiles will be introduced as people are ready to be named. Until then, every engagement still has a named owner and the specialists the scope requires.'),
		),
	),
	'insights' => array(
		'layout'           => 'insights',
		'wp_title'         => 'Insights',
		'nav_label'        => 'Insights',
		'title'            => 'Notes on building, marketing, and growing a digital business.',
		'eyebrow'          => 'Insights',
		'intro'            => 'Practical writing from the Sovassa team. The point is to make a decision easier, not to fill a calendar.',
		'meta_title'       => 'Insights | Sovassa Technologies',
		'meta_description' => 'Articles from Sovassa Technologies on technology, product, business, and marketing decisions.',
		'secondary_cta'    => array('label' => 'Explore services', 'url' => 'services'),
		'categories'       => array('Technology', 'Product', 'Business', 'Marketing', 'Founder', 'Proof', 'Sovassa'),
	),
	'careers' => array(
		'layout'           => 'careers',
		'wp_title'         => 'Careers',
		'nav_label'        => 'Careers',
		'title'            => 'Build with Sovassa.',
		'eyebrow'          => 'Careers',
		'intro'            => 'We are assembling a team that can design, ship, and market digital work without handing the story off at every boundary.',
		'meta_title'       => 'Careers | Sovassa Technologies',
		'meta_description' => 'Careers at Sovassa Technologies. See how we work, the teams we are building, and how to introduce yourself.',
		'primary_cta'      => array('label' => 'Introduce yourself', 'url' => '/careers/#apply'),
		'secondary_cta'    => array('label' => 'About the company', 'url' => 'about'),
		'why'              => array(
			array('title' => 'Work that reaches a customer', 'text' => 'Engineering, design, and marketing sit close enough to see whether the thing shipped is the thing people understood.'),
			array('title' => 'Room to practice judgement', 'text' => 'We would rather explain a tradeoff than hide it inside a template.'),
			array('title' => 'A company still taking shape', 'text' => 'Early teammates help decide how we scope, review, and talk to clients.'),
		),
		'teams'            => array(
			array('title' => 'Strategy and delivery', 'text' => 'Scoping, client communication, and keeping a project honest about its goal.'),
			array('title' => 'Design', 'text' => 'Research, interface design, and the system that lets engineering build without guesswork.'),
			array('title' => 'Engineering', 'text' => 'Web, mobile, and the integrations that make a product usable after launch.'),
			array('title' => 'Marketing', 'text' => 'SEO, content, paid media, and the reporting that shows what changed.'),
		),
		'culture'          => array(
			array('title' => 'Plain language', 'text' => 'We say what the work is for, including when we are not sure yet.'),
			array('title' => 'Work in the open', 'text' => 'Drafts and decisions are visible to the people who have to live with them.'),
			array('title' => 'The offer stays shared', 'text' => 'Design, engineering, and marketing are expected to recognise the same customer and the same promise.'),
		),
		'benefits'         => array(
			array('title' => 'Range across the work', 'text' => 'Early teammates see how a product and its marketing fit together, not only one queue of tickets.'),
			array('title' => 'Feedback with a reason', 'text' => 'Reviews are about the work, from a person who can explain the decision.'),
			array('title' => 'Zirakpur, and remote when the role allows', 'text' => 'The office is in Zirakpur, India. A real offer will say whether the role is on site, remote, or a mix. We will not imply benefits we have not defined.'),
		),
		'process'          => array(
			array('title' => 'Introduction', 'text' => 'Send a short note about the work you want to do and an example you are proud of.'),
			array('title' => 'Conversation', 'text' => 'We talk about how you make decisions, not only which tools you have used.'),
			array('title' => 'Practical discussion', 'text' => 'A bounded exercise or portfolio review, agreed in advance, relevant to the role.'),
			array('title' => 'Decision', 'text' => 'A clear yes, no, or not yet. We will not leave an application in silence.'),
		),
		'faq'              => array(
			array('q' => 'Are there open roles right now?', 'a' => 'No specific roles are listed yet. You can still introduce yourself if your work fits design, engineering, marketing, or delivery. We will keep the note and reply if there is a match.'),
			array('q' => 'Do you hire remotely?', 'a' => 'We expect much of the work to happen remotely. The office is in Zirakpur, India, and location is part of any real offer.'),
			array('q' => 'What should I send?', 'a' => 'Your name, email, the kind of work you want, and a link or short description of something you made. A long attachment is optional.'),
		),
	),
	'contact' => array(
		'layout'           => 'contact',
		'wp_title'         => 'Contact Us',
		'nav_label'        => 'Contact Us',
		'title'            => 'Tell us what you are trying to change.',
		'eyebrow'          => 'Contact',
		'intro'            => 'Share a short brief and we will reply with whether we can help, and what the first conversation should cover.',
		'meta_title'       => 'Contact Us | Sovassa Technologies',
		'meta_description' => 'Contact Sovassa Technologies about a website, product, SEO, or marketing project. Send a brief and we will reply with a next step.',
		'primary_cta'      => array('label' => 'Use the form', 'url' => '/contact/#enquiry'),
		'secondary_cta'    => array('label' => 'Get a quote instead', 'url' => 'get-a-quote'),
		'services'         => array(
			'Web development',
			'Mobile app development',
			'AI and automation',
			'UI/UX design',
			'SEO',
			'Digital marketing',
			'Social media',
			'Google Ads / PPC',
			'Content marketing',
			'Something else',
		),
	),
	'get-a-quote' => array(
		'layout'           => 'quote',
		'wp_title'         => 'Get a Quote',
		'nav_label'        => 'Free Consultation',
		'title'            => 'Request a free consultation.',
		'eyebrow'          => 'Start a project',
		'intro'            => 'Tell us the outcome you want. We will use it to prepare a useful first conversation, not a generic pitch.',
		'meta_title'       => 'Free Consultation | Sovassa Technologies',
		'meta_description' => 'Request a free consultation with Sovassa Technologies. Share your goal, timeline, and the services you need.',
		'primary_cta'      => array('label' => 'Start the form', 'url' => '/get-a-quote/#quote'),
		'secondary_cta'    => array('label' => 'Contact us', 'url' => 'contact'),
		'after'            => array(
			array('title' => 'We read the brief', 'text' => 'A person looks at what you sent. You will not get an automated quote for work we have not understood.'),
			array('title' => 'We reply with a next step', 'text' => 'That may be a short call, a few clarifying questions, or an honest note if we are not the right fit.'),
			array('title' => 'A proposal follows only if the work is clear', 'text' => 'Scope, timeline, and the way we would work together come after the conversation, not before it.'),
		),
		'services'         => array(
			'Web development',
			'Mobile apps',
			'AI and automation',
			'UI/UX design',
			'SEO',
			'Digital marketing',
			'Social media',
			'Paid media',
			'Content',
		),
		'timelines'        => array('As soon as possible', 'This quarter', 'This half', 'Planning ahead', 'Not sure yet'),
		'budgets'          => array('Still working it out', 'A defined project', 'An ongoing retainer', 'I would rather discuss it'),
	),
	'thank-you' => array(
		'layout'           => 'thankyou',
		'wp_title'         => 'Thank You',
		'nav_label'        => 'Thank You',
		'title'            => 'We have your note.',
		'eyebrow'          => 'Thank you',
		'intro'            => 'A person on the Sovassa team will read what you sent and reply with a next step.',
		'meta_title'       => 'Thank You | Sovassa Technologies',
		'meta_description' => 'Your message to Sovassa Technologies has been received.',
		'messages'         => array(
			'contact'     => 'Thanks for writing. We will reply to the email you entered.',
			'quote'       => 'Thanks for the consultation request. We will read the brief before we suggest a call.',
			'application' => 'Thanks for the introduction. We will be in touch if there is a matching conversation.',
			'newsletter'  => 'Thanks. We saved your address for future insights. You can still explore the articles that are already published.',
		),
	),
	'privacy' => array(
		'layout'           => 'privacy',
		'wp_title'         => 'Privacy Policy',
		'nav_label'        => 'Privacy Policy',
		'title'            => 'How we handle information on this website.',
		'eyebrow'          => 'Privacy Policy',
		'intro'            => 'This policy describes what Sovassa Technologies collects through sovassa.com, why we use it, and how to ask us about it. Last updated 25 September 2026.',
		'meta_title'       => 'Privacy Policy | Sovassa Technologies',
		'meta_description' => 'How Sovassa Technologies collects, uses, and stores information submitted through sovassa.com.',
		'sections'         => array(
			array('title' => 'Who we are', 'text' => 'Sovassa Technologies publishes this website. The office is in Zirakpur, India. Questions about this policy go to admin@sovassa.com.'),
			array('title' => 'What we collect', 'text' => 'If you submit a form, we store the fields you completed: typically your name, email, company, and the project note. Consultation forms may also include timeline, budget range, and website address. Careers notes and insight subscriptions use the same kind of form record. The site also receives routine technical data from your browser, such as the address of the page you requested, so the server can respond.'),
			array('title' => 'Why we use it', 'text' => 'We use form details to reply to you. Careers notes are kept so we can respond if a role matches. Newsletter addresses are kept so we can send occasional insights, and only if you asked for that. Technical data is used to run and protect the site.'),
			array('title' => 'Cookies', 'text' => 'Essential cookies keep the site working, including a cookie that remembers a choice you make in the cookie banner. Optional cookies, such as analytics or marketing cookies, stay off until you accept them. The Cookie Policy explains the categories and how to change your choice.'),
			array('title' => 'Where it is stored', 'text' => 'Form submissions are stored as private entries in this website’s WordPress admin. They are not published. Access is limited to people who operate the site. The site is hosted so those records can be kept and so we can email you a reply.'),
			array('title' => 'How long we keep it', 'text' => 'We keep enquiry records long enough to respond and to remember the context of a conversation. You can ask us to delete a submission by emailing admin@sovassa.com.'),
			array('title' => 'Who else sees it', 'text' => 'We do not sell form submissions. People who host the site or deliver email see information only so those services can run. We do not add your address to a marketing list unless you used the insights subscription and confirmed consent.'),
			array('title' => 'Your requests', 'text' => 'Email admin@sovassa.com to ask what we hold from a form you sent, to correct it, or to ask us to delete it. We will reply to the address you used, or to the address you give us for the request.'),
		),
	),
	'terms' => array(
		'layout'           => 'privacy',
		'wp_title'         => 'Terms & Conditions',
		'nav_label'        => 'Terms & Conditions',
		'title'            => 'Terms for using this website.',
		'eyebrow'          => 'Terms & Conditions',
		'intro'            => 'These terms cover use of sovassa.com. A paid project is governed by the proposal or agreement we both accept, not by browsing this site. Last updated 25 September 2026.',
		'meta_title'       => 'Terms & Conditions | Sovassa Technologies',
		'meta_description' => 'Terms for using the Sovassa Technologies website, and how project work is agreed separately.',
		'sections'         => array(
			array('title' => 'Who publishes the site', 'text' => 'Sovassa Technologies publishes sovassa.com. The office is in Zirakpur, India. You can write to admin@sovassa.com.'),
			array('title' => 'Using the site', 'text' => 'You may read the pages, send a form, and share links to public pages. Do not misuse the site, attempt to break it, or send a form with details you know are false.'),
			array('title' => 'Project work', 'text' => 'Reading a service page, requesting a consultation, or sending a message does not hire us and does not create a price or a deadline. Scope, fees, and timing are set only in a proposal or agreement that both sides accept.'),
			array('title' => 'Your messages', 'text' => 'What you send through a form is covered by the Privacy Policy. Please do not send confidential material until we have agreed how it should be handled.'),
			array('title' => 'Our content', 'text' => 'Text, design, and images on this site belong to Sovassa Technologies unless a page says otherwise. You may not copy them for your own commercial use without permission. How to raise a copyright concern is on the Copyright and DMCA page.'),
			array('title' => 'The site can change', 'text' => 'We may update pages, including these terms. The date on this page is the date of the current version. The site is offered as published. We do not promise that every page is free of errors or always available.'),
			array('title' => 'Responsibility', 'text' => 'To the extent the law allows, Sovassa Technologies is not liable for loss that comes from using the public website itself. Nothing on this page limits a right that the law does not allow us to limit. Questions about a live project belong with the agreement for that project.'),
		),
	),
	'cookies' => array(
		'layout'           => 'privacy',
		'wp_title'         => 'Cookie Policy',
		'nav_label'        => 'Cookie Policy',
		'title'            => 'How this website uses cookies.',
		'eyebrow'          => 'Cookie Policy',
		'intro'            => 'Cookies are small files a site stores on your browser. This page says which kinds this website uses and how you can choose. Last updated 25 September 2026.',
		'meta_title'       => 'Cookie Policy | Sovassa Technologies',
		'meta_description' => 'How Sovassa Technologies uses essential and optional cookies on sovassa.com.',
		'sections'         => array(
			array('title' => 'Essential cookies', 'text' => 'Essential cookies are required for the site to work. They include a cookie that remembers the choice you make in the cookie banner. These stay on because the site cannot honour that choice without them.'),
			array('title' => 'Optional cookies', 'text' => 'The banner can offer functional, analytics, and marketing cookies. Those stay off until you accept them. We do not treat a visit as permission for optional cookies.'),
			array('title' => 'Changing your choice', 'text' => 'Use the cookie banner or the cookie preferences control on the site to change what you accept. You can also clear cookies in your browser. Clearing them may forget a preference you already set, and the banner can appear again.'),
			array('title' => 'What cookies are not', 'text' => 'A cookie preference is not the same as a form you submit. Names, email addresses, and project notes from forms are described in the Privacy Policy, not stored as a marketing cookie unless you subscribed and confirmed consent.'),
		),
	),
	'copyright' => array(
		'layout'           => 'privacy',
		'wp_title'         => 'Copyright and DMCA',
		'nav_label'        => 'Copyright / DMCA',
		'title'            => 'Copyright and how to report a concern.',
		'eyebrow'          => 'Copyright / DMCA Policy',
		'intro'            => 'This page explains who owns the material on sovassa.com, what the DMCA.com badge means, and how to tell us about a copyright concern. Last updated 25 September 2026.',
		'meta_title'       => 'Copyright and DMCA Policy | Sovassa Technologies',
		'meta_description' => 'Copyright notice for the Sovassa Technologies website and how to report a copyright concern.',
		'sections'         => array(
			array('title' => 'Ownership', 'text' => 'Unless a page credits someone else, the text, design, and images on sovassa.com are owned by Sovassa Technologies. All rights are reserved. You may share a link to a public page. Copying the site for your own commercial use needs permission.'),
			array('title' => 'The DMCA.com badge', 'text' => 'The footer shows the official DMCA.com protection badge for this website. The badge links to the protection status DMCA.com publishes for our account. It is a status indicator from DMCA.com. It is not a government certification, and it does not mean a court has reviewed the site.'),
			array(
				'title' => 'Report a copyright concern',
				'text'  => 'If you believe material on this site uses your work without permission, email admin@sovassa.com. Include your name and contact details, a description of the work, the page address, and a statement that you believe the use is not authorised and that the information is accurate. We will review notices sent to that address and may remove the material while we look. This inbox is how Sovassa receives website copyright notices. It is not a statement that we are a registered agent with a copyright office.',
			),
		),
	),
);
