<?php
/**
 * Company, conversion, and insight pages.
 *
 * @package Sovassa
 */

return array(
	'home' => array(
		'layout'           => 'home',
		'wp_title'         => 'Home',
		'nav_label'        => 'Home',
		'title'            => 'A technology and marketing partner for',
		'rotate'           => array('Websites', 'Mobile products', 'Search growth', 'Automation'),
		'eyebrow'          => 'Build · Market · Grow',
		'intro'            => 'Sovassa Technologies designs and builds digital products, then markets them with the same team. The work stays tied to a business outcome instead of a pile of disconnected vendors.',
		'meta_title'       => 'Sovassa Technologies | Web, Product, and Digital Marketing',
		'meta_description' => 'Sovassa Technologies builds websites, apps, and AI products and markets them through SEO, content, and paid media. One team for build, market, and grow.',
		'trust'            => array(
			array('icon' => 'layers', 'label' => 'Technology and marketing, one team'),
			array('icon' => 'check', 'label' => 'Scoped work with a named next step'),
			array('icon' => 'globe', 'label' => 'Web, mobile, and applied AI'),
			array('icon' => 'search', 'label' => 'Search, content, and paid growth'),
		),
		'goals'            => array(
			array('title' => 'A website or web app', 'text' => 'Replace a site the team cannot edit, or ship a product people can actually use.', 'slug' => 'web-development'),
			array('title' => 'A mobile product', 'text' => 'Plan an iOS, Android, or cross-platform app around a real job to be done.', 'slug' => 'mobile-app-development'),
			array('title' => 'Qualified leads', 'text' => 'Give sales a clearer path from first visit to a conversation worth having.', 'slug' => 'solutions'),
			array('title' => 'Search visibility', 'text' => 'Make the services you sell easier to find, and easier to trust.', 'slug' => 'seo'),
			array('title' => 'Paid acquisition', 'text' => 'Run search and social campaigns that match the page a person lands on.', 'slug' => 'google-ads'),
			array('title' => 'Automation or AI', 'text' => 'Remove a repeated handoff, or add a practical AI workflow with a human check.', 'slug' => 'ai-automation'),
		),
		'why'              => array(
			array('title' => 'One thread from product to promotion', 'text' => 'The people who shape the offer also shape the site, the campaign, and the follow-up.'),
			array('title' => 'Decisions you can see', 'text' => 'Scope, milestones, and the measure of progress are written down before production starts.'),
			array('title' => 'Handover that stays usable', 'text' => 'You leave with a system your team can edit, not a file only we can open.'),
			array('title' => 'Growth after launch', 'text' => 'Reporting looks at enquiries, product use, and the next improvement, not a dashboard for its own sake.'),
		),
		'delivery'         => array(
			array('title' => 'Discover', 'text' => 'Understand the business, the audience, the current systems, and the constraint that actually matters.'),
			array('title' => 'Strategize', 'text' => 'Choose the offer, the pages or product scope, and the measure that will tell us the work is working.'),
			array('title' => 'Build', 'text' => 'Design, develop, write, or configure the approved work and review it in the open.'),
			array('title' => 'Grow', 'text' => 'Launch, support, and improve the parts that move enquiries, usage, or revenue.'),
		),
		'marketing'        => array(
			array('title' => 'Research', 'text' => 'Read the market, the current site, and the questions sales already hears.'),
			array('title' => 'Strategy', 'text' => 'Pick channels and messages that match how the company actually wins work.'),
			array('title' => 'Execute', 'text' => 'Publish, launch, and connect the work to the pages and forms that receive it.'),
			array('title' => 'Optimize', 'text' => 'Change the pieces that the numbers and the sales team both notice.'),
			array('title' => 'Report', 'text' => 'Share what changed, what did not, and the next decision in plain language.'),
		),
		'faq'              => array(
			array('q' => 'What does Sovassa Technologies do?', 'a' => 'We build websites, web apps, mobile products, and practical AI workflows, and we market them through SEO, content, social, and paid media. The point is to keep product and marketing in one plan.'),
			array('q' => 'Can we hire Sovassa for a single service?', 'a' => 'Yes. A website, a design engagement, an SEO program, or a paid media account can stand alone. We will say when a neighbouring service would change the result.'),
			array('q' => 'How does a project start?', 'a' => 'With a short consultation. We confirm the goal, the constraints, and whether we are the right team. If we are, you get a proposed scope and a way to begin.'),
			array('q' => 'Do you publish client metrics on this site?', 'a' => 'Only when they come from a completed engagement and the client is comfortable sharing them. Until then, the work page describes the kinds of problems we take on.'),
		),
	),
	'about' => array(
		'layout'           => 'about',
		'wp_title'         => 'About Us',
		'nav_label'        => 'About Us',
		'title'            => 'A company for teams that need the product and the marketing to agree.',
		'eyebrow'          => 'About Sovassa',
		'intro'            => 'Sovassa Technologies exists for companies whose website, product, and marketing were built as separate projects and no longer describe the same business.',
		'meta_title'       => 'About Us | Sovassa Technologies',
		'meta_description' => 'Sovassa Technologies is a technology and digital marketing company. We combine product building and marketing under one Build, Market, Grow model.',
		'story'            => array(
			'Sovassa is a new company, and we would rather say that plainly than invent a long history. The problem we are organised around is familiar: a business hires one team to build and another to promote, then spends the year translating between them.',
			'We bring those conversations into the same room. Strategy, design, engineering, and marketing share the offer, the audience, and the result the work is supposed to change.',
		),
		'vision'           => 'Companies should be able to explain what they do, ship the product that proves it, and reach the people who need it without starting over every quarter.',
		'mission'          => 'Help ambitious teams build useful digital products and market them with a plan that sales, marketing, and delivery can all recognise.',
		'values'           => array(
			array('title' => 'Clarity before decoration', 'text' => 'A page, a screen, or a campaign earns its place when a person can tell what to do next.'),
			array('title' => 'Honest scope', 'text' => 'We name what is included, what is not, and what we still need to learn.'),
			array('title' => 'Proof over performance', 'text' => 'We do not publish numbers we cannot stand behind. Real results will be added when they are real.'),
			array('title' => 'Systems people can keep', 'text' => 'The work should survive the project. Editing, reporting, and handover are part of the delivery.'),
		),
		'with_clients'     => array(
			array('title' => 'A named owner', 'text' => 'One person on our side keeps the thread, even when specialists join the work.'),
			array('title' => 'Shared working notes', 'text' => 'Decisions live where both teams can see them, not in a private chat.'),
			array('title' => 'Reviews with something to react to', 'text' => 'We show pages, flows, and drafts early enough to change them.'),
			array('title' => 'A finish line and a next step', 'text' => 'Launch includes what your team will do on Monday, not only a file handoff.'),
		),
		'capabilities'     => array(
			array('title' => 'Build', 'text' => 'Websites, web apps, mobile products, applied AI, and the interface design that holds them together.'),
			array('title' => 'Market', 'text' => 'SEO, content, social, and paid media aimed at the same offer the product describes.'),
			array('title' => 'Grow', 'text' => 'Measurement and packaged solutions that combine building and marketing around one result.'),
		),
		'why_choose'       => array(
			array('title' => 'One plan, not two vendors', 'text' => 'The people who shape the product also shape how it is explained and promoted.'),
			array('title' => 'Scope you can read', 'text' => 'What is included, what is not, and how progress will be judged are written down before production.'),
			array('title' => 'A handover the team can use', 'text' => 'Editing, reporting, and the next improvement are part of the delivery, not a later surprise.'),
		),
		'faq'              => array(
			array('q' => 'Where is Sovassa based?', 'a' => 'The office is in Zirakpur, India. We also work with clients remotely, and a proposal will say if a visit is useful.'),
			array('q' => 'Who will we work with?', 'a' => 'Team profiles will be introduced as people are ready to be named. Until then, every engagement still has a named owner and the specialists the scope requires.'),
		),
	),
	'insights' => array(
		'layout'           => 'insights',
		'wp_title'         => 'Insights',
		'nav_label'        => 'Insights',
		'title'            => 'Notes on building, marketing, and growing a digital business.',
		'eyebrow'          => 'Insights',
		'intro'            => 'Practical writing from the Sovassa team. The point is to make a decision easier, not to fill a calendar.',
		'meta_title'       => 'Insights | Sovassa Technologies',
		'meta_description' => 'Articles from Sovassa Technologies on technology, product, business, and marketing decisions.',
		'secondary_cta'    => array('label' => 'Explore services', 'url' => 'services'),
		'categories'       => array('Technology', 'Product', 'Business', 'Marketing', 'Founder', 'Proof', 'Sovassa'),
	),
	'careers' => array(
		'layout'           => 'careers',
		'wp_title'         => 'Careers',
		'nav_label'        => 'Careers',
		'title'            => 'Build with Sovassa.',
		'eyebrow'          => 'Careers',
		'intro'            => 'We are assembling a team that can design, ship, and market digital work without handing the story off at every boundary.',
		'meta_title'       => 'Careers | Sovassa Technologies',
		'meta_description' => 'Careers at Sovassa Technologies. See how we work, the teams we are building, and how to introduce yourself.',
		'primary_cta'      => array('label' => 'Introduce yourself', 'url' => '/careers/#apply'),
		'secondary_cta'    => array('label' => 'About the company', 'url' => 'about'),
		'why'              => array(
			array('title' => 'Work that reaches a customer', 'text' => 'Engineering, design, and marketing sit close enough to see whether the thing shipped is the thing people understood.'),
			array('title' => 'Room to practice judgement', 'text' => 'We would rather explain a tradeoff than hide it inside a template.'),
			array('title' => 'A company still taking shape', 'text' => 'Early teammates help decide how we scope, review, and talk to clients.'),
		),
		'teams'            => array(
			array('title' => 'Strategy and delivery', 'text' => 'Scoping, client communication, and keeping a project honest about its goal.'),
			array('title' => 'Design', 'text' => 'Research, interface design, and the system that lets engineering build without guesswork.'),
			array('title' => 'Engineering', 'text' => 'Web, mobile, and the integrations that make a product usable after launch.'),
			array('title' => 'Marketing', 'text' => 'SEO, content, paid media, and the reporting that shows what changed.'),
		),
		'culture'          => array(
			array('title' => 'Plain language', 'text' => 'We say what the work is for, including when we are not sure yet.'),
			array('title' => 'Work in the open', 'text' => 'Drafts and decisions are visible to the people who have to live with them.'),
			array('title' => 'The offer stays shared', 'text' => 'Design, engineering, and marketing are expected to recognise the same customer and the same promise.'),
		),
		'benefits'         => array(
			array('title' => 'Range across the work', 'text' => 'Early teammates see how a product and its marketing fit together, not only one queue of tickets.'),
			array('title' => 'Feedback with a reason', 'text' => 'Reviews are about the work, from a person who can explain the decision.'),
			array('title' => 'Zirakpur, and remote when the role allows', 'text' => 'The office is in Zirakpur, India. A real offer will say whether the role is on site, remote, or a mix. We will not imply benefits we have not defined.'),
		),
		'process'          => array(
			array('title' => 'Introduction', 'text' => 'Send a short note about the work you want to do and an example you are proud of.'),
			array('title' => 'Conversation', 'text' => 'We talk about how you make decisions, not only which tools you have used.'),
			array('title' => 'Practical discussion', 'text' => 'A bounded exercise or portfolio review, agreed in advance, relevant to the role.'),
			array('title' => 'Decision', 'text' => 'A clear yes, no, or not yet. We will not leave an application in silence.'),
		),
		'faq'              => array(
			array('q' => 'Are there open roles right now?', 'a' => 'No specific roles are listed yet. You can still introduce yourself if your work fits design, engineering, marketing, or delivery. We will keep the note and reply if there is a match.'),
			array('q' => 'Do you hire remotely?', 'a' => 'We expect much of the work to happen remotely. The office is in Zirakpur, India, and location is part of any real offer.'),
			array('q' => 'What should I send?', 'a' => 'Your name, email, the kind of work you want, and a link or short description of something you made. A long attachment is optional.'),
		),
	),
	'contact' => array(
		'layout'           => 'contact',
		'wp_title'         => 'Contact Us',
		'nav_label'        => 'Contact Us',
		'title'            => 'Tell us what you are trying to change.',
		'eyebrow'          => 'Contact',
		'intro'            => 'Share a short brief and we will reply with whether we can help, and what the first conversation should cover.',
		'meta_title'       => 'Contact Us | Sovassa Technologies',
		'meta_description' => 'Contact Sovassa Technologies about a website, product, SEO, or marketing project. Send a brief and we will reply with a next step.',
		'primary_cta'      => array('label' => 'Use the form', 'url' => '/contact/#enquiry'),
		'secondary_cta'    => array('label' => 'Get a quote instead', 'url' => 'get-a-quote'),
		'services'         => array(
			'Web development',
			'Mobile app development',
			'AI and automation',
			'UI/UX design',
			'SEO',
			'Digital marketing',
			'Social media',
			'Google Ads / PPC',
			'Content marketing',
			'Something else',
		),
	),
	'get-a-quote' => array(
		'layout'           => 'quote',
		'wp_title'         => 'Get a Quote',
		'nav_label'        => 'Free Consultation',
		'title'            => 'Request a free consultation.',
		'eyebrow'          => 'Start a project',
		'intro'            => 'Tell us the outcome you want. We will use it to prepare a useful first conversation, not a generic pitch.',
		'meta_title'       => 'Free Consultation | Sovassa Technologies',
		'meta_description' => 'Request a free consultation with Sovassa Technologies. Share your goal, timeline, and the services you need.',
		'primary_cta'      => array('label' => 'Start the form', 'url' => '/get-a-quote/#quote'),
		'secondary_cta'    => array('label' => 'Contact us', 'url' => 'contact'),
		'after'            => array(
			array('title' => 'We read the brief', 'text' => 'A person looks at what you sent. You will not get an automated quote for work we have not understood.'),
			array('title' => 'We reply with a next step', 'text' => 'That may be a short call, a few clarifying questions, or an honest note if we are not the right fit.'),
			array('title' => 'A proposal follows only if the work is clear', 'text' => 'Scope, timeline, and the way we would work together come after the conversation, not before it.'),
		),
		'services'         => array(
			'Web development',
			'Mobile apps',
			'AI and automation',
			'UI/UX design',
			'SEO',
			'Digital marketing',
			'Social media',
			'Paid media',
			'Content',
		),
		'timelines'        => array('As soon as possible', 'This quarter', 'This half', 'Planning ahead', 'Not sure yet'),
		'budgets'          => array('Still working it out', 'A defined project', 'An ongoing retainer', 'I would rather discuss it'),
	),
	'thank-you' => array(
		'layout'           => 'thankyou',
		'wp_title'         => 'Thank You',
		'nav_label'        => 'Thank You',
		'title'            => 'We have your note.',
		'eyebrow'          => 'Thank you',
		'intro'            => 'A person on the Sovassa team will read what you sent and reply with a next step.',
		'meta_title'       => 'Thank You | Sovassa Technologies',
		'meta_description' => 'Your message to Sovassa Technologies has been received.',
		'messages'         => array(
			'contact'     => 'Thanks for writing. We will reply to the email you entered.',
			'quote'       => 'Thanks for the consultation request. We will read the brief before we suggest a call.',
			'application' => 'Thanks for the introduction. We will be in touch if there is a matching conversation.',
			'newsletter'  => 'Thanks. We saved your address for future insights. You can still explore the articles that are already published.',
		),
	),
	'privacy' => array(
		'layout'           => 'privacy',
		'wp_title'         => 'Privacy',
		'nav_label'        => 'Privacy',
		'title'            => 'How we handle enquiries.',
		'eyebrow'          => 'Privacy',
		'intro'            => 'This note covers the forms on this website. It will be expanded if we add analytics tools or other processors.',
		'meta_title'       => 'Privacy | Sovassa Technologies',
		'meta_description' => 'How Sovassa Technologies uses the details you send through the website forms.',
		'sections'         => array(
			array('title' => 'What we collect', 'text' => 'If you submit a form, we store the fields you completed: typically your name, email, company, and the project note. Consultation forms may also include timeline, budget range, and website address.'),
			array('title' => 'Why we collect it', 'text' => 'We use those details to reply to you. Careers notes are kept so we can respond if a role matches. Newsletter addresses are kept so we can send occasional insights, and only if you asked for that.'),
			array('title' => 'Where it lives', 'text' => 'Submissions are stored as private entries in this website’s WordPress admin. They are not published. Access is limited to people who operate the site.'),
			array('title' => 'How long we keep it', 'text' => 'We keep enquiry records long enough to respond and to remember the context of a conversation. You can ask us to delete your submission by emailing admin@sovassa.com, or by sending another form that says deletion.'),
			array('title' => 'What we do not do', 'text' => 'We do not sell form submissions. We do not add your address to a marketing list unless you used the insights subscription and confirmed consent.'),
		),
	),
);
