<?php
/**
 * Industry detail pages. Each market is its own URL.
 *
 * @package Sovassa
 */

$industry_parent = array('label' => 'Industries', 'slug' => 'industries');

return array(
	'industries/professional-services' => array(
		'layout'           => 'industry',
		'wp_title'         => 'Professional Services',
		'nav_label'        => 'Professional services',
		'title'            => 'Professional services websites that show the offer.',
		'eyebrow'          => 'Industries',
		'intro'            => 'Expertise is hard to see when the website reads like a list of departments. The page should name the work a buyer can hire, and the conversation that comes next.',
		'bridge'           => 'The usual start is one page per offer, through',
		'meta_title'       => 'Professional Services Websites | Sovassa Technologies',
		'meta_description' => 'Websites, content, and SEO for professional services firms whose expertise is hard to see, and whose website still reads like a list of departments today.',
		'crumb_parent'     => $industry_parent,
		'secondary_cta'    => array('label' => 'All industries', 'url' => 'industries'),
		'challenge'        => 'Partners sell through conversations, then send a website that lists practice areas without saying who the work is for. A visitor cannot tell which offer to enquire about, so the enquiry is vague or it never arrives.',
		'support'          => 'We give each offer a page, a proof point the firm can actually stand behind, and one way to start a conversation. Thought leadership is written to support those pages, not to fill a calendar.',
		'points'           => array(
			array('title' => 'One page per offer', 'text' => 'Practice areas stop sharing a single paragraph. Each service says who it is for and what happens after the first call.'),
			array('title' => 'Language sales already uses', 'text' => 'The site uses the explanation partners already give in meetings, so proposals and pages stop disagreeing.'),
			array('title' => 'A calmer enquiry path', 'text' => 'The form asks for the matter, not a generic message, and it reaches a person who owns the reply.'),
		),
		'services'         => array('web-development', 'content-marketing', 'seo'),
		'faq'              => array(
			array('q' => 'Do you write the service pages?', 'a' => 'Yes, when content is part of the engagement. We draft from how the firm already sells, and your team approves anything that describes the work.'),
			array('q' => 'Will you publish client names?', 'a' => 'Only when the firm is comfortable sharing them. Until then the page describes the offer, not a borrowed result.'),
		),
	),
	'industries/ecommerce' => array(
		'layout'           => 'industry',
		'wp_title'         => 'Ecommerce',
		'nav_label'        => 'Ecommerce',
		'title'            => 'Ecommerce sites where the offer matches the shelf.',
		'eyebrow'          => 'Industries',
		'intro'            => 'The catalogue and the campaigns drift apart when different people plan them. The store, the collections, and the ads need to describe the same products.',
		'bridge'           => 'Store work usually starts with the catalogue and the pages campaigns can land on, through',
		'meta_title'       => 'Ecommerce Websites and Marketing | Sovassa Technologies',
		'meta_description' => 'Storefront, collection structure, and acquisition work for ecommerce teams whose catalogue and campaigns were planned apart and no longer match the shelves.',
		'crumb_parent'     => $industry_parent,
		'secondary_cta'    => array('label' => 'All industries', 'url' => 'industries'),
		'challenge'        => 'Merchandising, content, and acquisition were never planned together. Ads promise an offer the collection page does not show, and the catalogue is hard to shop for the products that can actually sell.',
		'support'          => 'We improve the shopping paths that matter, tidy the collection structure, and point SEO or paid media at pages that can convert. Campaigns are not planned against a catalogue nobody owns.',
		'points'           => array(
			array('title' => 'Collections a buyer can use', 'text' => 'Categories follow how people shop, not only how the warehouse is labelled.'),
			array('title' => 'Campaigns that land on a real product', 'text' => 'Search and paid traffic go to a collection or product that matches the ad, not a generic homepage.'),
			array('title' => 'A store the team can edit', 'text' => 'Merchandising changes should not wait on a developer for every seasonal update.'),
		),
		'services'         => array('web-development', 'seo', 'google-ads'),
		'faq'              => array(
			array('q' => 'Do you rebuild the whole store?', 'a' => 'Only when the current store cannot support the catalogue or the checkout path. Often the first job is structure, content, and the pages campaigns already use.'),
			array('q' => 'Can paid media start before the store is ready?', 'a' => 'We will say when a landing page is not ready to receive the traffic. Spending against a mismatched collection is not a launch plan.'),
		),
	),
	'industries/healthcare' => array(
		'layout'           => 'industry',
		'wp_title'         => 'Healthcare',
		'nav_label'        => 'Healthcare',
		'title'            => 'Healthcare pages with a careful next step.',
		'eyebrow'          => 'Industries',
		'intro'            => 'Patients and referrers need to know what to do next. The content has to stay careful, and the form has to reach the right desk.',
		'bridge'           => 'The careful part is the journey and the next step, shaped through',
		'meta_title'       => 'Healthcare Websites and Content | Sovassa Technologies',
		'meta_description' => 'Journey design, plain-language pages, and careful forms for healthcare teams. Patients and referrers get a next step. Clinical claims are not invented.',
		'crumb_parent'     => $industry_parent,
		'secondary_cta'    => array('label' => 'All industries', 'url' => 'industries'),
		'challenge'        => 'Services are described in language a clinician understands and a patient does not. Referrers cannot see how to send someone, and the form lands in a shared inbox with no owner.',
		'support'          => 'We design the journey, write plain-language pages, and route forms to the desk that should receive them. We do not invent clinical claims, outcomes, or credentials.',
		'points'           => array(
			array('title' => 'A page for the decision', 'text' => 'Each service explains who it is for, what happens first, and what the page will not promise.'),
			array('title' => 'Separate paths for patients and referrers', 'text' => 'The next step is different for someone booking care and someone sending a patient. The site should not force them through the same form.'),
			array('title' => 'Claims the organisation can defend', 'text' => 'Copy is reviewed by the team that is accountable for it. We will not add results, awards, or medical statements that are not supplied.'),
		),
		'services'         => array('ui-ux-design', 'web-development', 'content-marketing'),
		'faq'              => array(
			array('q' => 'Do you write clinical content?', 'a' => 'We draft in plain language from material you provide. A qualified person on your side approves anything that describes care, outcomes, or eligibility.'),
			array('q' => 'Can the site collect patient details?', 'a' => 'Only the details your team is prepared to receive and store. We will not add a form that asks for more than the follow-up process can handle.'),
		),
	),
	'industries/education' => array(
		'layout'           => 'industry',
		'wp_title'         => 'Education',
		'nav_label'        => 'Education',
		'title'            => 'Education sites that help someone choose a program.',
		'eyebrow'          => 'Industries',
		'intro'            => 'Programs are many, and a prospective student cannot tell which one is theirs. The site should make the choice visible before it asks for an application.',
		'bridge'           => 'Program choice is a page problem first. Campaigns help only after a course can receive the visit, often starting with',
		'meta_title'       => 'Education Websites and Campaigns | Sovassa Technologies',
		'meta_description' => 'Information architecture, program pages, and campaigns for education teams whose prospective students still cannot tell which course or intake is theirs.',
		'crumb_parent'     => $industry_parent,
		'secondary_cta'    => array('label' => 'All industries', 'url' => 'industries'),
		'challenge'        => 'Every program shares a template that hides the differences: who it is for, how long it takes, and what the next intake requires. Campaigns land on a general page, so the enquiry is for “more information” rather than a course.',
		'support'          => 'We organise the information architecture, give important programs their own pages, and send campaigns to a specific course or intake. The student should be able to tell whether this one is theirs.',
		'points'           => array(
			array('title' => 'Program pages with a difference', 'text' => 'Duration, audience, and the next intake are visible. Similar courses are not copies of each other with the name swapped.'),
			array('title' => 'A path that matches the campaign', 'text' => 'An ad or email about one course lands on that course, not on a list of every program the institution runs.'),
			array('title' => 'Editors who can update an intake', 'text' => 'Dates and requirements change. The team that owns admissions should be able to change them without a rebuild.'),
		),
		'services'         => array('ui-ux-design', 'web-development', 'digital-marketing'),
		'faq'              => array(
			array('q' => 'Do you need a page for every course?', 'a' => 'No. Start with the programs people actually ask about or search for. A long list of thin pages is worse than a smaller set that explains the choice.'),
			array('q' => 'Can campaigns promote a single intake?', 'a' => 'Yes. That is the useful version. The landing page should name the intake, the deadline, and what happens after someone enquires.'),
		),
	),
	'industries/real-estate' => array(
		'layout'           => 'industry',
		'wp_title'         => 'Real Estate',
		'nav_label'        => 'Real estate',
		'title'            => 'Real estate lead paths the team can follow up.',
		'eyebrow'          => 'Industries',
		'intro'            => 'Leads arrive faster than follow-up, and listings or services are hard to compare. The site should make the next conversation possible, not only collect a phone number.',
		'bridge'           => 'Lead paths usually need a page people can compare, and sometimes a handoff for the repeated step, starting with',
		'meta_title'       => 'Real Estate Websites and Lead Paths | Sovassa Technologies',
		'meta_description' => 'Lead paths, listing or service pages, and follow-up for real estate teams whose enquiries arrive faster than anyone on the team can respond to them well.',
		'crumb_parent'     => $industry_parent,
		'secondary_cta'    => array('label' => 'All industries', 'url' => 'industries'),
		'challenge'        => 'Listings or services look alike, so a visitor cannot compare them. Enquiries pile into a shared inbox, and the person who should call does not see them until the moment has passed.',
		'support'          => 'We shape the lead path, present properties or services so they can be compared, and hand the enquiry to the tool the team already uses. Automation is for the repeated handoff, not a replacement for the conversation.',
		'points'           => array(
			array('title' => 'Listings or services that can be compared', 'text' => 'The facts a buyer uses to decide are in the same place on every page, not buried in a brochure.'),
			array('title' => 'An owner for the reply', 'text' => 'The form records what the person wants and reaches the desk that is supposed to respond.'),
			array('title' => 'Follow-up that is already a habit', 'text' => 'We connect the enquiry to the system the team uses. We do not add a second inbox nobody checks.'),
		),
		'services'         => array('web-development', 'google-ads', 'ai-automation'),
		'faq'              => array(
			array('q' => 'Do you build a listings portal?', 'a' => 'When the business needs one. If listings already live in another system, the first job is often the service pages and the path from an ad into that system.'),
			array('q' => 'Will paid leads help if follow-up is slow?', 'a' => 'Not by themselves. We will not scale the ads until someone owns the reply and the page matches what the ad promised.'),
		),
	),
	'industries/software-and-startups' => array(
		'layout'           => 'industry',
		'wp_title'         => 'Software and Startups',
		'nav_label'        => 'Software and startups',
		'title'            => 'A marketing site that can keep up with the product.',
		'eyebrow'          => 'Industries',
		'intro'            => 'The product is moving, and the marketing site is either absent or already out of date. For tech startups, early buyers need a plain explanation and a way to reach the team.',
		'bridge'           => 'For tech startups, the usual start is a launch site that can keep up with the product, through',
		'meta_title'       => 'Software and Startup Marketing Sites | Sovassa Technologies',
		'meta_description' => 'Launch sites, product UX, and a small content or paid program for software companies whose marketing site is missing, thin, or already out of date now.',
		'crumb_parent'     => $industry_parent,
		'secondary_cta'    => array('label' => 'All industries', 'url' => 'industries'),
		'challenge'        => 'The product changes faster than the website. Screenshots, pricing, and the description of the job disagree. Sometimes there is no site at all, only a deck.',
		'support'          => 'We ship a launch site in the same language as the product, design the path a new user takes, and add only the content or paid work that helps the team learn from early users.',
		'points'           => array(
			array('title' => 'The site matches the current product', 'text' => 'The offer, the screenshot, and the signup describe the version a person will actually get.'),
			array('title' => 'A first path, not a full brand system', 'text' => 'Early companies need a page that explains the job and collects a real conversation. A finished brand can wait.'),
			array('title' => 'Learning from the first users', 'text' => 'A small content or paid program is useful when it tells the team who is arriving and what they ask.'),
		),
		'services'         => array('web-development', 'ui-ux-design', 'content-marketing'),
		'faq'              => array(
			array('q' => 'Is this the same as a startup MVP?', 'a' => 'Related, and separate. This page is for the company site around a software product. The startup page is for a first release that still has to teach the team something.'),
			array('q' => 'How often should the site change?', 'a' => 'When the offer changes. We set the site up so the team can update the story without treating every product release as a redesign.'),
		),
	),
	'industries/saas' => array(
		'layout'           => 'industry',
		'wp_title'         => 'SaaS',
		'nav_label'        => 'SaaS',
		'title'            => 'SaaS marketing that matches the product.',
		'eyebrow'          => 'Industries',
		'intro'            => 'The product and the website often describe different versions of the same subscription. A new account should meet the workflow the site just promised.',
		'bridge'           => 'The useful pairing is onboarding and marketing pages that describe the same subscription, starting with',
		'meta_title'       => 'SaaS Product and Marketing Websites | Sovassa Technologies',
		'meta_description' => 'Onboarding, the core workflow, and marketing pages for SaaS products whose website still describes a different version of the subscription than the app.',
		'crumb_parent'     => $industry_parent,
		'secondary_cta'    => array('label' => 'All industries', 'url' => 'industries'),
		'challenge'        => 'Marketing pages describe a plan, a feature, or an outcome the product no longer leads with. Onboarding then asks the new customer to discover the real job on their own.',
		'support'          => 'We align the core workflow, the onboarding path, and the marketing pages so they use the same language. Content explains the job the subscription does, not a feature list from an older release.',
		'points'           => array(
			array('title' => 'One description of the product', 'text' => 'The homepage, the pricing page, and the first screen of the app should be recognisable as the same offer.'),
			array('title' => 'Onboarding for the job, not the tour', 'text' => 'A new account is pointed at the workflow that creates value, not a checklist of every feature.'),
			array('title' => 'Pages that can change with the plan', 'text' => 'When pricing or packaging changes, the site has a place to say so without rewriting the whole product story.'),
		),
		'services'         => array('web-development', 'ui-ux-design', 'content-marketing'),
		'faq'              => array(
			array('q' => 'Do you build the SaaS product itself?', 'a' => 'When the engagement includes product development. This page is also for teams that already have a product and need the site, onboarding, and explanation to catch up.'),
			array('q' => 'Will you invent usage numbers?', 'a' => 'No. Proof on the site comes from a result the company can share. Until then the page describes the workflow, not a metric we made up.'),
		),
	),
	'industries/startups' => array(
		'layout'           => 'industry',
		'wp_title'         => 'Startups',
		'nav_label'        => 'Startups',
		'title'            => 'A first release and a site that can learn.',
		'eyebrow'          => 'Industries',
		'intro'            => 'The first version has to teach the team something, and the site cannot wait for a finished brand. Buyers need a plain offer and a way to respond. This is a different job from a marketing site for an existing software product.',
		'bridge'           => 'A first release usually needs a small site and a plain explanation, through',
		'meta_title'       => 'Startup Websites and First Releases | Sovassa Technologies',
		'meta_description' => 'An MVP or launch site, a plain offer, and a way to learn from first enquiries, for startups that cannot wait until the brand feels finished enough to launch.',
		'crumb_parent'     => $industry_parent,
		'secondary_cta'    => array('label' => 'All industries', 'url' => 'industries'),
		'challenge'        => 'The idea is larger than the first release, and the company is waiting to look finished before it talks to buyers. The site, when it exists, describes a vision instead of a job someone can try.',
		'support'          => 'We cut the first version to one job, ship a launch site that explains it, and leave a way to hear from the first enquiries. The brand can stay plain until the offer is real.',
		'points'           => array(
			array('title' => 'One job in the first version', 'text' => 'The release is small enough to learn from. Features that do not serve that job wait.'),
			array('title' => 'A site that says what exists', 'text' => 'The page describes the current offer, who it is for, and how to start. It does not preview a product that is not available.'),
			array('title' => 'A record of what people ask', 'text' => 'Enquiries are specific enough that the next version can respond to them, not only to the original pitch.'),
		),
		'services'         => array('web-development', 'ui-ux-design', 'content-marketing'),
		'faq'              => array(
			array('q' => 'Do you need a full brand before the site?', 'a' => 'No. A clear name, a plain explanation, and a page people can trust are enough to learn. Visual polish can follow once the offer is stable.'),
			array('q' => 'Is a startup page different from SaaS?', 'a' => 'Yes. SaaS work assumes a subscription product that marketing must describe accurately. A startup engagement is the first release and the first conversation with buyers.'),
		),
	),
	'industries/fintech' => array(
		'layout'           => 'industry',
		'wp_title'         => 'Fintech',
		'nav_label'        => 'Fintech',
		'title'            => 'Fintech explanations people can trust.',
		'eyebrow'          => 'Industries',
		'intro'            => 'People need to understand the product before they share money or data. The explanation is often too vague to trust, or too dense to finish.',
		'bridge'           => 'Trust starts with a journey people can finish, and language that does not invent a permission, through',
		'meta_title'       => 'Fintech Product Design and Websites | Sovassa Technologies',
		'meta_description' => 'Clear journeys and careful language for fintech products. People need to trust the next step before they share money or data. We do not invent claims.',
		'crumb_parent'     => $industry_parent,
		'secondary_cta'    => array('label' => 'All industries', 'url' => 'industries'),
		'challenge'        => 'The product asks for money or data before the page has explained what happens next. Risk, fees, or the limit of the service are either missing or written so densely that people skip them.',
		'support'          => 'We design the journey, write careful language, and show the next step on the product screens. We do not invent regulatory status, returns, or protections the company has not documented.',
		'points'           => array(
			array('title' => 'The next step is visible', 'text' => 'Before someone shares money or data, the page says what they are asked for and what they receive.'),
			array('title' => 'Limits written in plain language', 'text' => 'Fees, eligibility, and what the product does not do are part of the explanation, not a footnote nobody reaches.'),
			array('title' => 'No borrowed trust', 'text' => 'Badges, licences, and performance claims appear only when the company can show them. We will not imply a permission that is not there.'),
		),
		'services'         => array('ui-ux-design', 'web-development', 'content-marketing'),
		'faq'              => array(
			array('q' => 'Do you handle licensing or compliance filings?', 'a' => 'No. We design and write the customer-facing explanation. Regulatory claims are supplied by your team and checked by whoever is accountable for them.'),
			array('q' => 'Can the page stay short?', 'a' => 'Yes. Short is useful when it is specific. A vague headline with the detail hidden in a policy PDF is the pattern we are trying to replace.'),
		),
	),
);
