<?php
/**
 * Insight articles from the content-pillar plan.
 *
 * Titles follow the brand content sheet. Bodies are original Sovassa notes.
 *
 * @package Sovassa
 */

/**
 * Pillar articles to seed.
 *
 * @return array<int, array<string, string>>
 */
function sovassa_pillar_posts() {
	$items = array(
		array('Product', 'How much does it cost to build an app?', 'A useful cost conversation starts with the job, the users, and the first release, not a single number.'),
		array('Product', 'How long does app development take?', 'A date is only real after the first release has a boundary.'),
		array('Product', 'MVP vs full product', 'An MVP is a learning release. A full product is a commitment to operate what you learned.'),
		array('Technology', 'Native vs cross-platform', 'Choose the approach from the product, not from the framework that is fashionable.'),
		array('Technology', 'Flutter vs React Native', 'Both can ship a shared app. The better fit is the one your team can keep changing.'),
		array('Product', 'Signs your business needs an app', 'An app earns its place when a repeated job is worse on a website.'),
		array('Product', 'When you should not build an app', 'A phone icon is not a strategy. Some products should stay on the web.'),
		array('Product', 'How to validate an app idea', 'Validation is a conversation with the people who would use the first version.'),
		array('Technology', 'Common app development mistakes', 'Most failed apps were unclear before the first line of code.'),
		array('Business', 'How to choose an app development company', 'Ask who owns the product decision, not only who can write the code.'),
		array('Technology', 'How much does a business website cost?', 'Website cost follows the number of decisions, not the number of pages alone.'),
		array('Technology', 'Website redesign checklist', 'A redesign should change what a visitor can do, not only how the site looks.'),
		array('Marketing', 'Why websites do not generate leads', 'Traffic cannot fix a page that never asks for a conversation.'),
		array('Marketing', 'Landing page vs website', 'A landing page sells one offer. A website has to hold the rest of the company.'),
		array('Product', 'Website UX mistakes', 'The expensive mistakes are structural: people cannot tell what to do next.'),
		array('Technology', 'Website speed and conversion', 'Speed matters when it gets in the way of the next step, not as a score for its own sake.'),
		array('Marketing', 'How to build a B2B website', 'A B2B site should sound like the sales conversation, then make that conversation easy to start.'),
		array('Technology', 'Website architecture', 'Architecture is the map of pages, jobs, and the system that will edit them.'),
		array('Technology', 'CMS comparison', 'Pick a CMS for the people who will publish after launch.'),
		array('Technology', 'Website launch checklist', 'Launch is a list of checks, not a mood.'),
		array('Marketing', 'SEO vs paid advertising', 'Search and paid answer different timings. Most companies need to know which job each one has.'),
		array('Marketing', 'How long SEO takes', 'SEO shows up as clearer pages before it shows up as a traffic chart.'),
		array('Marketing', 'Why traffic does not equal leads', 'A visit is not an enquiry. The page in between has to do some work.'),
		array('Marketing', 'B2B lead generation', 'A lead is a person the sales team can recognise, not a form fill with no owner.'),
		array('Marketing', 'Content marketing strategy', 'A strategy names the pages the writing is supposed to support.'),
		array('Marketing', 'LinkedIn for B2B companies', 'LinkedIn helps when it continues a point the website already makes.'),
		array('Marketing', 'Website conversion optimisation', 'Optimise the step a real visitor hesitates on.'),
		array('Marketing', 'Digital marketing funnel', 'A funnel is the path from attention to a conversation, written down.'),
		array('Business', 'Marketing metrics businesses should track', 'Track the numbers a team will use to change the work.'),
		array('Business', 'How technology and marketing should work together', 'The site, the product, and the campaign should describe the same offer.'),
	);

	$bodies = array(
		'<p>There is no honest single price for an app. A first release that lets one type of user finish one job is a different product from an app with accounts, payments, offline use, and an admin team.</p><p>Ask what the first version must do, who is excluded on purpose, and which systems it has to talk to. Those answers move the cost more than the choice of iOS or Android. Store release, the month of fixes after launch, and a way for the team to change copy also belong in the same estimate.</p><p>Sovassa does not publish a calculator. A consultation can give a range after the job is clear. A number before that is a guess.</p>',
		'<p>Time follows the same boundary as cost. A small release with a known job can be planned in weeks. A product that still has four undecided audiences will spend those weeks in meetings.</p><p>Count discovery, design of the critical journeys, build, device testing, and store review. Leave room for the first fixes. A date that ignores review is a launch announcement, not a plan.</p><p>If the business needs to learn something by a particular month, cut the release until that date can hold the learning. Do not keep the feature list and hope the calendar stretches.</p>',
		'<p>An MVP is the smallest version that lets real users complete the core job. It is not a rough draft of every screen you might want later. If nobody can name the job, you do not have an MVP. You have a feature list.</p><p>A fuller product is what you build after that use is visible: more roles, more edge cases, and the operational tools the team needs. Skipping the learning release usually means building the edge cases first.</p><p>Sovassa scopes the first slice so the next decision can be made from use, not from a longer workshop.</p>',
		'<p>Native apps are the right call when the product depends on the platform: camera behaviour, performance, or interface habits people already know on that phone. Cross-platform is the right call when most of the product is shared and the device-specific surface is small.</p><p>Two codebases cost more to keep aligned. One codebase costs more when you later need behaviour the shared layer does not do well. The choice should be written down after discovery, with the reason attached.</p><p>Either path still needs the same product work: journeys, empty states, permissions, and a plan for the month after release.</p>',
		'<p>Flutter and React Native both let a team share most of an app across iOS and Android. Flutter is a strong fit when the interface should be consistent and the team is ready to work in that toolkit. React Native is a strong fit when the team already lives in JavaScript and the product can use that.</p><p>The framework does not decide the product. Accounts, offline behaviour, and store release are the same problem in both. Pick the one the people who will maintain the app can actually change six months later.</p><p>If nobody on the team will keep the app, the choice should include who that person will be.</p>',
		'<p>A business needs an app when people repeat a job that a website handles badly: something they do often, often away from a desk, or with the phone’s own capabilities. Ordering, field work, and a daily operational task are common examples.</p><p>It is a weaker sign if the only goal is “customers expect an app” and the website already does the job. An unused app is a second product to maintain.</p><p>Write down the job, how often it happens, and what is painful on the current site. If that sentence is hard to finish, stay on the web a little longer.</p>',
		'<p>Do not build an app to decorate a brochure site, to follow a competitor, or to postpone a website that is already unclear. A phone will not make a vague offer specific.</p><p>Wait when the process is still changing every week, when you cannot name the user, or when the team cannot support a store release and the fixes that follow. Those are product problems, and an app will freeze them.</p><p>A focused site, or a narrower tool inside the site, is often the honest first step.</p>',
		'<p>Validation means checking the job with the people who would use the first version. Talk to them before you commission screens of every idea. Ask what they do today, what they abandon, and what would have to be true for them to switch.</p><p>A clickable journey of the core task is enough to test the idea. A full build is not. If the conversations disagree with each other, the idea is not ready. The disagreement is the finding.</p><p>Sovassa treats that check as part of framing the product, not as a separate workshop with no consequence for the scope.</p>',
		'<p>The common mistakes are familiar. The app copies a website. iOS and Android drift apart because nobody owns the shared behaviour. Accounts and permissions appear late. The store listing is treated as someone else’s job. The first month of fixes was never in the plan.</p><p>A feature list written before the job is named will produce all of those. So will a design that cannot change when a journey fails in testing.</p><p>Name the job, design that path, and leave a person responsible after release. The rest of the backlog can wait.</p>',
		'<p>Choose a company that can say no to part of the brief. Ask who will decide the first release, who will design the journeys, and who will be there after the store approves the app. A portfolio of screens is not the same answer.</p><p>Ask how they choose native or cross-platform, and what they refuse to invent: prices, timelines, and results they have not measured. The reply should be specific to your job, not a package.</p><p>Sovassa starts with that conversation. If the problem is not one we should take, we say so before a proposal.</p>',
		'<p>A business website costs more when it has to explain several offers, collect a lead the right team can see, and be edited without a developer. A single landing page is a smaller job. A logged-in portal is a different job again.</p><p>Content, the editing model, and the systems the form must reach belong in the estimate. A low price that leaves those out is a later invoice.</p><p>We do not publish a price list. After a look at the current site and the job, a consultation can give a range.</p>',
		'<p>Start with what the current site fails to do. Visitors cannot tell the offer. The team cannot edit it. Enquiries land in the wrong place. Those are the reasons to redesign. A new colour is not.</p><p>Then agree the pages that matter, the one next step on each, and who will update them. Check the content you can reuse and the content that should be rewritten. Only then look at the interface.</p><p>Before launch, read the site as a stranger: the service, the proof you actually have, and the way to enquire should be obvious.</p>',
		'<p>A website fails to generate leads when the offer is vague, the page never asks, or the form reaches nobody. More traffic will not repair that. It will only make the silence louder.</p><p>Give each important service its own page, one reason to trust it, and one way to start. Make sure a person owns the replies. Then, and only then, spend money or effort sending people there.</p><p>If sales already explains the offer well in conversation, the page should sound like that explanation.</p>',
		'<p>A landing page is for one campaign or one offer. It has a single next step and almost no other job. A website is the place the rest of the company lives: services, proof, and a way for someone who was not in the campaign to understand you.</p><p>Sending paid traffic to the homepage usually wastes the click. Sending every visitor to a landing page usually hides the company. Use both, and make them say the same thing.</p><p>Build the page the campaign promises before you buy the traffic.</p>',
		'<p>The mistakes that cost enquiries are rarely a font. People cannot tell which service is theirs. The navigation is a map of the org chart. Forms ask for more than the team will use. Mobile is a squeezed desktop. There is no empty state and no confirmation after someone writes to you.</p><p>Fix the path first: arrival, understanding, and the next step. Visual polish on a confused path makes the confusion look finished.</p><p>Test the path with someone who does not work on the site. Their hesitation is the brief.</p>',
		'<p>A slow site loses people who were ready to read or enquire. That is the conversion problem. A perfect speed score on a page with no offer does not create a lead.</p><p>Keep templates light, images sized, and the important content visible without waiting on extras. Measure the pages that receive campaigns, not only the homepage.</p><p>Treat speed as part of the build, then watch whether enquiries move. If they do not, the offer or the form is the next place to look.</p>',
		'<p>A B2B website should help a buyer explain you internally. Name the services, who they are for, and what happens after an enquiry. Avoid a homepage that could belong to any firm in the category.</p><p>Service pages do more work than a slogan. So does a clear way to contact the right desk. Proof can wait until a client is willing to be named. A vague claim is worse than a plain description.</p><p>Write the pages in the language sales already uses. The site should not invent a second company.</p>',
		'<p>Website architecture is which pages exist, what each one is for, and how a person moves between them. It is also how an editor will add the next page without breaking the structure.</p><p>Group pages by the way buyers look for you: services, problems, and the few industries you can speak about specifically. Do not create a page only to increase the count.</p><p>The address of each page, the title, and the internal links should make that map obvious to a person and to search.</p>',
		'<p>Compare a CMS by who edits, how often, and what they must be able to change. WordPress fits marketing sites a team will keep publishing. A custom or headless setup fits when the product is really an application. Webflow fits when a visual editor is the publishing model you want. Shopify fits a store.</p><p>Do not choose from a feature grid alone. Sit with the person who will change a headline next month and see whether the tool matches them.</p><p>The wrong CMS is the one only the agency can open.</p>',
		'<p>Before a site goes live, check the pages a buyer will actually use. Titles, forms, the inbox those forms reach, and the confirmation a person sees. Check it on a phone. Check that editors can change a page without breaking the layout.</p><p>Also check speed on the important templates, basic security updates, and that search can find the addresses you intend to publish. Remove sample content.</p><p>Launch when that list is done. A launch date that skips it is a public draft.</p>',
		'<p>Paid advertising can put a specific offer in front of people this week. SEO makes the pages you own easier to find for the services you intend to keep selling. They are not substitutes.</p><p>Use paid when you have a page that continues the promise and a person who will handle the replies. Use SEO when the site’s structure and wording match real searches. Using both without that page wastes both.</p><p>Decide the job of each channel for the quarter. Adding every channel is not a strategy.</p>',
		'<p>Technical cleanup and clearer service pages can be done in weeks. A change in how often the right people find you takes longer, and it depends on competition and on whether the pages deserve to rank.</p><p>Do not promise a position. Do promise the work: pages that match real queries, a site that can be crawled, and a way to see enquiries rather than only visits.</p><p>If leadership needs a result this month, paid or a clearer sales path is the honest tool. SEO is the asset you build beside that.</p>',
		'<p>Traffic is people arriving. A lead is someone the business can respond to. The gap is the page, the offer, and the follow-up. A popular article that never points at a service will not fill a pipeline.</p><p>Look at which pages receive visits and whether those pages ask for the right next step. Then look at whether anyone owns the reply. Fix that before you buy more visits.</p><p>Report both numbers. A chart of sessions alone will flatter a site that does not sell.</p>',
		'<p>B2B lead generation starts with a definition. Which enquiry is worth a sales conversation, and which is not? Write that down so marketing and sales are not counting different things.</p><p>Then build the page and the form that collect it, and point the campaign or the search work at that page. A shared inbox with no owner will waste a good page.</p><p>Review the leads with the people who follow up. If they would not call them, the definition or the page is wrong.</p>',
		'<p>A content strategy is a short list of topics that make the service pages clearer. Each piece should help a buyer, a sales conversation, or the team that has to explain the offer again.</p><p>A calendar without that link produces posts the site does not need. Publish less, and attach each piece to a page you already want found.</p><p>Repurpose only after the point is useful on the site. Social posts can carry the same idea. They should not be the only place it exists.</p>',
		'<p>LinkedIn is useful for a B2B company when the people you want already pay attention there, and when you have a point of view the website can support. A post that the site contradicts is just noise.</p><p>Write from real work: how you scope, what you refuse, and the decisions buyers ask about. Do not invent client stories to fill the feed.</p><p>Point the useful posts back to a page that continues the explanation. The network is a door, not the whole office.</p>',
		'<p>Conversion work looks at a specific hesitation. People leave before they understand the service. They understand it and do not trust the next step. They submit and never hear back. Each one has a different fix.</p><p>Change one thing you can explain: the heading, the form, the proof you actually have, or the page a campaign lands on. Then see whether enquiries change. A redesign of everything at once teaches you nothing.</p><p>Keep a note of what you changed and why, so the next month does not undo it by accident.</p>',
		'<p>A useful funnel names the stages you can actually see: a person finds the offer, understands it, starts a conversation, and becomes a customer or does not. It is not a diagram with a dozen labels nobody measures.</p><p>For each stage, name the page or the message that does the work, and the person who owns the handoff. If a stage has no owner, it is a slogan.</p><p>Sovassa plans channels against that path. A channel without a stage to serve can wait.</p>',
		'<p>Track enquiries that match the definition you agreed, the pages that produce them, and the campaigns that send people to those pages. Track response time if follow-up is part of the promise.</p><p>Visits, followers, and impressions are context. They are not the result. A metric nobody will use to change next month’s work should leave the report.</p><p>Review the few numbers in a meeting where someone can decide to stop, keep, or change a piece of work.</p>',
		'<p>Technology and marketing split when the product, the website, and the campaign describe three versions of the company. Buyers feel that split even if the teams do not.</p><p>Put one owner on the offer. The site should use the same words as the sales conversation. Campaigns should land on a page that continues the promise. Automation should support a handoff a person still owns.</p><p>That is the reason Sovassa keeps build and market in one plan. Separate vendors can still do the work. They should not invent separate companies.</p>',
	);

	$posts = array();
	foreach ($items as $index => $item) {
		$posts[] = array(
			'slug'     => sanitize_title($item[1]),
			'title'    => $item[1],
			'category' => $item[0],
			'excerpt'  => $item[2],
			'content'  => $bodies[$index],
		);
	}
	return $posts;
}
