<?php
/**
 * Solutions, industries, work, and technologies.
 *
 * @package Sovassa
 */

return array(
	'solutions' => array(
		'layout'           => 'solutions',
		'wp_title'         => 'Solutions',
		'nav_label'        => 'Solutions',
		'title'            => 'Start from the business problem, then choose the services.',
		'eyebrow'          => 'Grow',
		'intro'            => 'Solutions package Build and Market work around an outcome. Use them when you know the result you need and want Sovassa to recommend the mix.',
		'meta_title'       => 'Growth and Product Solutions | Sovassa Technologies',
		'meta_description' => 'Sovassa solutions package web, product, and marketing work for pipeline growth, ecommerce, SaaS, automation, new launches, and enterprise software builds.',
		'secondary_cta'    => array('label' => 'Browse services', 'url' => 'services'),
		'items'            => array(
			array(
				'title'    => 'B2B growth',
				'problem'  => 'The pipeline depends on referrals, and the website does not help a buyer understand the offer.',
				'solution' => 'Clarify the services, rebuild the pages that sales already sends, and add the search or content work that matches those conversations.',
				'services' => array('Web development', 'SEO', 'Content marketing'),
			),
			array(
				'title'    => 'Ecommerce growth',
				'problem'  => 'The store exists, but merchandising, content, and acquisition were never planned together.',
				'solution' => 'Improve the shopping paths that matter, then connect SEO and paid media to the collections that can actually convert.',
				'services' => array('Web development', 'SEO', 'Google Ads'),
			),
			array(
				'title'    => 'Lead generation',
				'problem'  => 'Traffic or attention arrives, and the follow-up is a shared inbox with no owner.',
				'solution' => 'Define a qualified enquiry, build the page and form that collect it, and align the campaign that sends people there.',
				'services' => array('Digital marketing', 'Google Ads', 'Web development'),
			),
			array(
				'title'    => 'Business automation',
				'problem'  => 'The same brief, status, or report is rebuilt by hand every week.',
				'solution' => 'Map the handoff, automate the repeated step, and leave a person in charge of the exceptions.',
				'services' => array('AI and automation', 'Web development'),
			),
			array(
				'title'    => 'Digital transformation',
				'problem'  => 'Tools were added one at a time, and the customer journey crosses four of them without a map.',
				'solution' => 'Choose the system of record, redesign the customer-facing path, and retire the steps that no longer earn their place.',
				'services' => array('UI/UX design', 'Web development', 'AI and automation'),
			),
			array(
				'title'    => 'New business launch',
				'problem'  => 'A new offer needs a name in the market, a place to send people, and a way to learn from the first enquiries.',
				'solution' => 'Ship a focused site, a clear story, and the minimum marketing needed to hear from real buyers.',
				'services' => array('UI/UX design', 'Web development', 'Content marketing'),
			),
			array(
				'title'    => 'MVP development',
				'problem'  => 'The idea is larger than the first release, and nobody has agreed what “enough to learn” means.',
				'solution' => 'Cut the product to one job, ship that version, and decide the next slice from what users actually do.',
				'services' => array('UI/UX design', 'Mobile apps', 'Web development'),
			),
			array(
				'title'    => 'SaaS development',
				'problem'  => 'A software product needs accounts, billing, and a way for a new customer to reach value without a demo.',
				'solution' => 'Design the core workflow, build the product around it, and give the marketing site the same language as the app.',
				'services' => array('Web development', 'UI/UX design', 'Content marketing'),
			),
			array(
				'title'    => 'eCommerce development',
				'problem'  => 'The business needs a store, not only campaigns pointed at a catalogue someone else owns.',
				'solution' => 'Build the shop, the catalogue structure, and the checkout path, then connect acquisition to the collections that can sell.',
				'services' => array('Web development', 'UI/UX design', 'Google Ads'),
			),
			array(
				'title'    => 'Product development',
				'problem'  => 'The roadmap is a feature list, and the product still does not have a clear first user.',
				'solution' => 'Name the user and the job, design that path, and build it in reviewable slices.',
				'services' => array('UI/UX design', 'Web development', 'Mobile apps'),
			),
			array(
				'title'    => 'Startup development',
				'problem'  => 'A young company needs a product, a site, and a way to hear from the first buyers at the same time.',
				'solution' => 'Ship a small product or site, a plain explanation of the offer, and the minimum marketing needed to learn.',
				'services' => array('Web development', 'UI/UX design', 'Content marketing'),
			),
			array(
				'title'    => 'Enterprise software',
				'problem'  => 'The work crosses teams, permissions, and systems that cannot be replaced in one release.',
				'solution' => 'Map the system of record, design the path people actually use, and integrate instead of asking the company to start over.',
				'services' => array('Web development', 'AI and automation', 'UI/UX design'),
			),
		),
		'combine'          => 'A solution is not a new service with a different logo. It is a recommended combination, scoped as one engagement with one owner. You can still buy any service on its own.',
	),
	'industries' => array(
		'layout'           => 'industries',
		'wp_title'         => 'Industries',
		'nav_label'        => 'Industries',
		'title'            => 'The same capabilities, shaped around how a market buys.',
		'eyebrow'          => 'Industries',
		'intro'            => 'Sovassa does not pretend every industry is identical. These are the markets we can describe specifically. Each one has its own page, written from the problem we see, not from a client result we do not have.',
		'meta_title'       => 'Industries We Build and Market For | Sovassa Technologies',
		'meta_description' => 'How Sovassa applies web, product, and marketing work in SaaS, startups, ecommerce, healthcare, education, real estate, fintech, and professional services.',
		'secondary_cta'    => array('label' => 'See illustrative work', 'url' => 'work'),
		'items'            => array(
			array(
				'title'       => 'Professional services',
				'slug'        => 'industries/professional-services',
				'challenge'   => 'Expertise is hard to see, and the website reads like a list of departments.',
				'support'     => 'Service pages, thought leadership, and a calmer enquiry path for partners who sell through conversations.',
				'combination' => 'Web, content, SEO',
			),
			array(
				'title'       => 'Ecommerce',
				'slug'        => 'industries/ecommerce',
				'challenge'   => 'The catalogue and the campaigns are planned by different people, so offers do not match the shelves.',
				'support'     => 'Storefront improvements, collection structure, and acquisition pointed at pages that can convert.',
				'combination' => 'Web, SEO, paid media',
			),
			array(
				'title'       => 'Healthcare',
				'slug'        => 'industries/healthcare',
				'challenge'   => 'Patients and referrers need clear next steps, and the content has to stay careful.',
				'support'     => 'Journey design, plain-language pages, and forms that reach the right desk. We do not invent clinical claims.',
				'combination' => 'UX, web, content',
			),
			array(
				'title'       => 'Education',
				'slug'        => 'industries/education',
				'challenge'   => 'Programs are many, and a prospective student cannot tell which one is theirs.',
				'support'     => 'Information architecture, program pages, and campaigns that land on a specific course or intake.',
				'combination' => 'UX, web, digital marketing',
			),
			array(
				'title'       => 'Real estate',
				'slug'        => 'industries/real-estate',
				'challenge'   => 'Leads arrive faster than follow-up, and listings or services are hard to compare.',
				'support'     => 'Lead paths, property or service presentation, and the handoff into the tool the team already uses.',
				'combination' => 'Web, paid media, automation',
			),
			array(
				'title'       => 'Software and startups',
				'slug'        => 'industries/software-and-startups',
				'challenge'   => 'The product is moving, and the marketing site is either absent or already out of date.',
				'support'     => 'A launch site, product UX, and a small content or paid program that learns from early users.',
				'combination' => 'Product, UX, content',
			),
			array(
				'title'       => 'SaaS',
				'slug'        => 'industries/saas',
				'challenge'   => 'The product and the website describe different versions of the same subscription.',
				'support'     => 'Onboarding, the core workflow, and marketing pages that match what a new account actually does.',
				'combination' => 'Product, UX, content',
			),
			array(
				'title'       => 'Startups',
				'slug'        => 'industries/startups',
				'challenge'   => 'The first version has to teach the team something, and the site cannot wait for a finished brand.',
				'support'     => 'An MVP or launch site, a plain offer, and a way to learn from the first enquiries.',
				'combination' => 'Product, web, content',
			),
			array(
				'title'       => 'Fintech',
				'slug'        => 'industries/fintech',
				'challenge'   => 'People need to trust the product before they share money or data, and the explanation is often too vague or too dense.',
				'support'     => 'Clear journeys, careful language, and product screens that show what happens next. We do not invent regulatory claims.',
				'combination' => 'UX, web, content',
			),
		),
		'faq'              => array(
			array('q' => 'Do you only work in these industries?', 'a' => 'No. They are the ones we can speak about specifically today. If your market is different, the consultation is the right place to see whether the problem is one we know how to approach.'),
			array('q' => 'Will there be a page for my industry?', 'a' => 'Each market listed here has its own page. If yours is not listed, the consultation is the place to see whether the problem is one we know how to approach.'),
		),
	),
	'work' => array(
		'layout'           => 'work',
		'wp_title'         => 'Case Studies',
		'nav_label'        => 'Case Studies',
		'title'            => 'The kinds of work Sovassa takes on.',
		'eyebrow'          => 'Our work',
		'intro'            => 'Named case studies and measured results will be published when a client engagement is complete and the client is comfortable sharing them. Until then, these cards describe the shape of web development services, app development, and digital marketing services. They are not a finished portfolio.',
		'meta_title'       => 'Case Studies and Engagement Types | Sovassa Technologies',
		'meta_description' => 'The web development services, app development, SEO, and digital marketing services Sovassa takes on. Named results appear only when a client can share them.',
		'secondary_cta'    => array('label' => 'Talk about a project', 'url' => 'get-a-quote'),
		'items'            => array(
			array(
				'title'      => 'A services website with a clearer enquiry path',
				'text'       => 'Restructure a professional-services site so each offer has a page, a proof point, and one obvious way to start a conversation.',
				'challenge'  => 'The site lists departments, and a visitor cannot tell which offer to enquire about.',
				'solution'   => 'Give each offer its own page, one proof point, and a single way to start a conversation.',
				'result'     => 'A measured result will be published when a completed engagement of this kind can be shared.',
				'service'    => 'Web Development',
				'industry'   => 'Professional services',
				'technology' => 'WordPress',
			),
			array(
				'title'      => 'A first mobile release around one job',
				'text'       => 'Define the task a phone should handle, design that journey, and ship a first version with a plan for the month after release.',
				'challenge'  => 'The app brief is a feature list before anyone has named the job the phone should do.',
				'solution'   => 'Define that job, design the journey, and ship a first version with a plan for the month after release.',
				'result'     => 'A measured result will be published when a completed engagement of this kind can be shared.',
				'service'    => 'Mobile Apps',
				'industry'   => 'Software and startups',
				'technology' => 'Cross-platform',
			),
			array(
				'title'      => 'Search and pages for a company that sells expertise',
				'text'       => 'Pair a technical cleanup with service pages written in the language buyers already search for.',
				'challenge'  => 'The company sells expertise, but the pages do not match the words buyers already search for.',
				'solution'   => 'Clean up the technical basics and rewrite the service pages in that language.',
				'result'     => 'A measured result will be published when a completed engagement of this kind can be shared.',
				'service'    => 'SEO',
				'industry'   => 'Professional services',
				'technology' => 'SEO',
			),
			array(
				'title'      => 'Paid search pointed at a real landing page',
				'text'       => 'Separate buying queries from research queries, and send each to a page that continues the promise in the ad.',
				'challenge'  => 'Ads and the website make different promises, so paid traffic arrives and leaves.',
				'solution'   => 'Separate buying queries from research queries, and send each to a page that continues the ad.',
				'result'     => 'A measured result will be published when a completed engagement of this kind can be shared.',
				'service'    => 'Google Ads',
				'industry'   => 'Ecommerce',
				'technology' => 'Google Ads',
			),
			array(
				'title'      => 'A repeated handoff turned into a workflow',
				'text'       => 'Take a weekly copy-paste between inbox and tracker and replace the repeated step, with a person still approving exceptions.',
				'challenge'  => 'The same information is copied by hand between an inbox and a tracker every week.',
				'solution'   => 'Replace that repeated step, and keep a person approving the exceptions.',
				'result'     => 'A measured result will be published when a completed engagement of this kind can be shared.',
				'service'    => 'AI and automation',
				'industry'   => 'Software and startups',
				'technology' => 'Automation',
			),
			array(
				'title'      => 'A launch site for a new offer',
				'text'       => 'Ship a small site, a plain explanation of the offer, and the minimum content needed to learn from the first enquiries.',
				'challenge'  => 'A new offer has no page that explains it in the words a first buyer needs.',
				'solution'   => 'Ship a small site, a plain explanation, and enough content to learn from the first enquiries.',
				'result'     => 'A measured result will be published when a completed engagement of this kind can be shared.',
				'service'    => 'Content Marketing',
				'industry'   => 'Education',
				'technology' => 'Content',
			),
		),
	),
	'technologies' => array(
		'layout'           => 'technologies',
		'wp_title'         => 'Technologies',
		'nav_label'        => 'Technologies',
		'title'            => 'The stack we plan around.',
		'eyebrow'          => 'Technologies',
		'intro'            => 'These are tools and platforms Sovassa is prepared to use. Mobile development technologies we will actually propose include Swift, Kotlin, Flutter, and React Native. Listing any of them is not a partnership claim. The project, the editors, and the team who will own it decide the final choice.',
		'meta_title'       => 'Web, Mobile, and Marketing Stack | Sovassa Technologies',
		'meta_description' => 'The web, mobile, AI, cloud, CMS, and analytics tools Sovassa Technologies actually uses to design, build, and market digital products for client work.',
		'secondary_cta'    => array('label' => 'See services', 'url' => 'services'),
		'groups'           => array(
			array('title' => 'Frontend', 'items' => array('React', 'Next.js', 'Vue', 'TypeScript', 'Modern CSS')),
			array('title' => 'Backend', 'items' => array('Node.js', 'PHP', 'Laravel', 'Python', 'REST APIs')),
			array('title' => 'Mobile', 'items' => array('Swift', 'Kotlin', 'Flutter', 'React Native')),
			array('title' => 'AI and automation', 'items' => array('Workflow automation', 'LLM APIs', 'Retrieval over approved documents', 'Product integrations')),
			array('title' => 'Cloud and delivery', 'items' => array('AWS', 'Docker', 'CI pipelines', 'Managed WordPress hosting')),
			array('title' => 'CMS and commerce', 'items' => array('WordPress', 'Headless CMS', 'Shopify')),
			array('title' => 'Analytics and marketing', 'items' => array('GA4', 'Search Console', 'Tag Manager', 'Google Ads', 'Looker Studio')),
		),
	),
);
