<?php
/**
 * Services hub and service detail pages.
 *
 * @package Sovassa
 */

$service_faq_common = array(
	array(
		'q' => 'Can this service stand alone?',
		'a' => 'Yes. We will tell you if another capability would change the outcome, and you can decide whether to include it.',
	),
	array(
		'q' => 'How do we start?',
		'a' => 'Send a consultation request with the goal, the current site or product if you have one, and the timing you have in mind.',
	),
);

return array(
	'services' => array(
		'layout'           => 'services',
		'wp_title'         => 'Services',
		'nav_label'        => 'Services',
		'title'            => 'Technology and marketing, planned as one offer.',
		'eyebrow'          => 'Our services',
		'intro'            => 'Sovassa groups the work into Build, Market, and Grow so you can start with a service and still see how it connects to the rest of the customer journey.',
		'meta_title'       => 'Services | Sovassa Technologies',
		'meta_description' => 'Sovassa Technologies services span web and mobile development, AI, UI/UX, SEO, digital marketing, social, paid media, and content.',
		'secondary_cta'    => array('label' => 'See solutions', 'url' => 'solutions'),
		'together'         => array(
			array('title' => 'Build', 'text' => 'The product or website a person actually uses.'),
			array('title' => 'Market', 'text' => 'The channels that bring the right people to it.'),
			array('title' => 'Grow', 'text' => 'The operating rhythm that improves both after launch.'),
		),
		'engagements'      => array(
			array('title' => 'Fixed project', 'text' => 'A defined scope, milestones, and a delivery plan for a specific piece of work.', 'points' => array('Website or product build', 'Design system', 'Campaign launch', 'Migration')),
			array('title' => 'Monthly retainer', 'text' => 'Ongoing improvement when priorities shift and the work should not restart every month.', 'points' => array('SEO', 'Content', 'Paid media', 'Product improvements')),
			array('title' => 'Flexible support', 'text' => 'A smaller block of time for consulting, fixes, or a question that does not need a full project.', 'points' => array('Advisory', 'QA and fixes', 'Tracking setup', 'Reviews')),
		),
		'faq'              => array(
			array('q' => 'What services does Sovassa offer?', 'a' => 'Build covers web development, mobile apps, AI and automation, and UI/UX design. Market covers SEO, digital marketing, social media, Google Ads, and content. Grow covers packaged solutions that combine those services around a business outcome.'),
			array('q' => 'Can you combine website and marketing work?', 'a' => 'Yes. That is the reason the company is structured this way. Shared goals keep the page, the offer, and the campaign from drifting apart.'),
			array('q' => 'Which platforms do you use?', 'a' => 'The Technologies page lists the stack we actually plan around, including modern JavaScript, PHP and WordPress, mobile frameworks, cloud hosting, and common analytics tools. We choose the stack for the job rather than forcing one platform.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'web-development' => array(
		'layout' => 'service', 'pillar' => 'build', 'wp_title' => 'Web Development', 'nav_label' => 'Web Development',
		'title' => 'Websites and web applications built around a next step.',
		'eyebrow' => 'Build',
		'card' => 'Marketing sites, portals, dashboards, and web apps your team can keep using.',
		'intro' => 'We design and develop websites and web applications that explain the offer, support the team behind it, and stay fast enough to trust.',
		'meta_title' => 'Web Development Services | Sovassa Technologies',
		'meta_description' => 'Sovassa builds marketing websites, portals, dashboards, and web applications with a clear handover and room to grow.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Most web projects stall for reasons that are not the framework.',
		'challenges' => array(
			array('title' => 'The site no longer matches the offer', 'text' => 'Pages were added over years. A visitor cannot tell what you sell or who it is for.'),
			array('title' => 'Editing depends on a developer', 'text' => 'Small copy changes wait in a queue, so the site falls behind the sales conversation.'),
			array('title' => 'The form does not reach the team', 'text' => 'Enquiries arrive somewhere nobody owns, and follow-up is improvised.'),
			array('title' => 'Performance and structure were deferred', 'text' => 'The site looks finished and still feels slow, fragile, or impossible to extend.'),
		),
		'delivers' => array(
			array('title' => 'Marketing websites', 'text' => 'Service, industry, and campaign pages with a path to enquire.'),
			array('title' => 'Web applications', 'text' => 'Authenticated tools, portals, and workflows with a defined set of users.'),
			array('title' => 'Dashboards', 'text' => 'Internal views of the numbers and tasks a team already chases in spreadsheets.'),
			array('title' => 'Content systems', 'text' => 'WordPress or a headless CMS, chosen for who will edit the site after launch.'),
		),
		'capabilities' => array('Information architecture', 'Responsive interface development', 'CMS setup and editor training', 'Forms and basic integrations', 'Performance and accessibility passes', 'Launch and handover notes'),
		'stack' => array('WordPress', 'PHP', 'React', 'Next.js', 'Laravel', 'Headless CMS'),
		'offers' => array(
			array('title' => 'Custom websites', 'text' => 'A site designed around the offer, not a theme with the logo swapped.'),
			array('title' => 'WordPress', 'text' => 'Marketing and content sites the team can edit after launch.'),
			array('title' => 'Webflow', 'text' => 'Designed pages with a visual editor when that is the right publishing model.'),
			array('title' => 'Shopify', 'text' => 'A store structured around collections, checkout, and the campaigns that send people there.'),
			array('title' => 'eCommerce', 'text' => 'Catalogue, merchandising, and the pages a buyer needs before they pay.'),
			array('title' => 'Web applications', 'text' => 'Logged-in tools, portals, and workflows with a defined set of users.'),
			array('title' => 'Landing pages', 'text' => 'A page written for one campaign or one offer, with a single next step.'),
			array('title' => 'Website redesign', 'text' => 'A new structure and interface for a site that no longer matches the business.'),
			array('title' => 'Website maintenance', 'text' => 'Updates, fixes, and small improvements after the site is live.'),
		),
		'process' => array(
			array('title' => 'Discover', 'text' => 'Map the audience, the pages that matter, and the systems the site must talk to.'),
			array('title' => 'Shape', 'text' => 'Agree the sitemap, the editing model, and the interactions worth designing in detail.'),
			array('title' => 'Build', 'text' => 'Develop in reviewable slices, with content and tracking included rather than bolted on.'),
			array('title' => 'Launch', 'text' => 'Check quality, speed, and the handover your team will use the following week.'),
		),
		'quality' => 'We treat performance, security updates, editor permissions, and a sensible content model as part of the build. Scalability means the next page or integration has an obvious place to live.',
		'related' => array('ui-ux-design', 'seo', 'content-marketing'),
		'faq' => array(
			array('q' => 'Do you build in WordPress?', 'a' => 'Yes, when editing and marketing pages are the priority. We use a custom front end when the product is really an application. The choice is part of discovery, not a default.'),
			array('q' => 'Can you improve a site we already have?', 'a' => 'Often. We will say if a rebuild is the honest recommendation after looking at the theme, the content, and the editor experience.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'mobile-app-development' => array(
		'layout' => 'service', 'pillar' => 'build', 'wp_title' => 'Mobile App Development', 'nav_label' => 'Mobile Apps',
		'title' => 'Mobile products with a reason to exist on a phone.',
		'eyebrow' => 'Build',
		'card' => 'iOS, Android, and cross-platform apps planned around a job to be done.',
		'intro' => 'We help teams shape, design, and ship mobile apps when the phone is genuinely the right place for the task.',
		'meta_title' => 'Mobile App Development | Sovassa Technologies',
		'meta_description' => 'Sovassa designs and builds iOS, Android, and cross-platform mobile apps, including UX, QA, and release support.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Mobile work fails when the app is a smaller copy of a website nobody asked to carry in a pocket.',
		'challenges' => array(
			array('title' => 'The job is unclear', 'text' => 'Stakeholders want an app before they can name the repeated task it should remove.'),
			array('title' => 'iOS and Android drift apart', 'text' => 'Two codebases, two backlogs, and a design that fits neither platform well.'),
			array('title' => 'Accounts and data are an afterthought', 'text' => 'Sign-in, permissions, and offline behaviour appear late and reshape the product.'),
			array('title' => 'Release is treated as the end', 'text' => 'Store review, crash reporting, and the first month of fixes were never in the plan.'),
		),
		'delivers' => array(
			array('title' => 'Product definition', 'text' => 'The journeys, roles, and release slice that deserve a first version.'),
			array('title' => 'iOS and Android', 'text' => 'Native or cross-platform implementation, chosen for the product rather than habit.'),
			array('title' => 'Integrations', 'text' => 'APIs, notifications, and the admin tools the team needs to operate the app.'),
			array('title' => 'Release support', 'text' => 'Store submission, QA notes, and a plan for the issues that show up after launch.'),
		),
		'capabilities' => array('Journey mapping', 'Interface design for mobile', 'Cross-platform or native build', 'API integration', 'QA on real devices', 'Store release support'),
		'stack' => array('Swift', 'Kotlin', 'Flutter', 'React Native', 'REST APIs', 'Push notifications'),
		'offers' => array(
			array('title' => 'iOS', 'text' => 'Native iPhone and iPad apps when platform behaviour is part of the product.'),
			array('title' => 'Android', 'text' => 'Native Android apps for the devices and versions your users actually have.'),
			array('title' => 'Flutter', 'text' => 'One codebase for iOS and Android when the product can share most of the interface.'),
			array('title' => 'React Native', 'text' => 'Cross-platform apps when the team already works in the JavaScript ecosystem.'),
			array('title' => 'Cross-platform', 'text' => 'A shared app where the first release does not need two separate codebases.'),
			array('title' => 'MVP', 'text' => 'The smallest release that lets real users complete the core job.'),
			array('title' => 'Enterprise apps', 'text' => 'Apps with roles, permissions, and the systems a larger organisation already runs.'),
			array('title' => 'App UI/UX', 'text' => 'Research, journeys, and interface design before or alongside the build.'),
			array('title' => 'App maintenance', 'text' => 'Fixes, store updates, and the first months after release.'),
			array('title' => 'App modernization', 'text' => 'A planned rebuild or upgrade of an app that is hard to change or no longer fits the platform.'),
		),
		'process' => array(
			array('title' => 'Frame the product', 'text' => 'Decide who the app is for and which task the first release must complete.'),
			array('title' => 'Design the journeys', 'text' => 'Prototype the critical paths before engineering commits to them.'),
			array('title' => 'Build in slices', 'text' => 'Ship reviewable increments with tracking and empty states included.'),
			array('title' => 'Release and watch', 'text' => 'Prepare store assets, test, and leave a clear path for the first fixes.'),
		),
		'quality' => 'QA, permission handling, and a basic security review of accounts and data are part of the engagement. We do not treat the store listing as someone else’s problem.',
		'related' => array('ui-ux-design', 'web-development', 'ai-automation'),
		'faq' => array(
			array('q' => 'Should we build native or cross-platform?', 'a' => 'Cross-platform is often right for a shared product with a modest device-specific surface. Native is right when platform behaviour is the product. We recommend one after discovery.'),
			array('q' => 'Do you design the app as well?', 'a' => 'Yes. Interface and engineering can be scoped together or alongside an existing design, as long as the flows are allowed to change when they do not hold up.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'ai-automation' => array(
		'layout' => 'service', 'pillar' => 'build', 'wp_title' => 'AI & Automation', 'nav_label' => 'AI & Automation',
		'title' => 'Practical AI and automation for work you already do.',
		'eyebrow' => 'Build',
		'card' => 'Workflows, assistants, and integrations with a human check and a clear boundary.',
		'intro' => 'We apply automation and AI where a repeated task is already understood, and we leave it alone where the process is still changing every week.',
		'meta_title' => 'AI and Automation Services | Sovassa Technologies',
		'meta_description' => 'Sovassa designs practical AI workflows and business automation with clear data boundaries and human review.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'The opportunity is rarely “add AI”. It is a handoff that wastes the same hour every day.',
		'challenges' => array(
			array('title' => 'Work lives in inboxes', 'text' => 'Requests, briefs, and status updates are retyped between tools.'),
			array('title' => 'People do not trust the output', 'text' => 'A generated draft has no owner, no source, and no way to reject it.'),
			array('title' => 'Data boundaries are vague', 'text' => 'Customer or internal information might be pasted into tools nobody has reviewed.'),
			array('title' => 'The demo never becomes a process', 'text' => 'A prototype impresses a meeting and never reaches the team that would use it.'),
		),
		'delivers' => array(
			array('title' => 'Workflow automation', 'text' => 'Handoffs between the tools you already use, with a record of what happened.'),
			array('title' => 'Assistive drafting', 'text' => 'First drafts for support, content, or internal notes, with a person approving the send.'),
			array('title' => 'Internal knowledge tools', 'text' => 'A bounded assistant over documents you choose, not an open-ended chatbot.'),
			array('title' => 'Product features', 'text' => 'An AI capability inside a web or mobile product, scoped like any other feature.'),
		),
		'capabilities' => array('Process mapping', 'Integration design', 'Prompt and workflow setup', 'Human review steps', 'Access and data boundaries', 'A rollback if the workflow misbehaves'),
		'stack' => array('Workflow tools', 'API integrations', 'LLM APIs', 'Python', 'Web apps', 'Analytics events'),
		'process' => array(
			array('title' => 'Find the repeated task', 'text' => 'Watch the work long enough to name the step worth automating.'),
			array('title' => 'Bound the data', 'text' => 'Decide what the system may read, store, and show, and what it must not.'),
			array('title' => 'Build the smallest loop', 'text' => 'A workflow one team can run, with a way to correct mistakes.'),
			array('title' => 'Review before you expand', 'text' => 'Keep it only if the people doing the job trust it.'),
		),
		'quality' => 'Responsible implementation here means a named owner, a data boundary, and a way to turn the workflow off. We do not ship an assistant that nobody is accountable for.',
		'related' => array('web-development', 'digital-marketing', 'solutions'),
		'faq' => array(
			array('q' => 'Do you train custom models?', 'a' => 'Not as a default. Most useful work is a workflow, a retrieval boundary, or a product feature on top of an existing model. Custom training is a different project and we will say if it is unnecessary.'),
			array('q' => 'Is our content sent to a third party?', 'a' => 'Only if we agree that in the scope. The design includes which provider is used and what is allowed to leave your systems.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'ui-ux-design' => array(
		'layout' => 'service', 'pillar' => 'build', 'wp_title' => 'UI/UX Design', 'nav_label' => 'UI/UX Design',
		'title' => 'Design that makes the next step obvious.',
		'eyebrow' => 'Build',
		'card' => 'Research, journeys, interface design, and a handover engineering can build.',
		'intro' => 'We research, structure, and design interfaces for websites and products, then hand them to engineering with the decisions still attached.',
		'meta_title' => 'UI/UX Design Services | Sovassa Technologies',
		'meta_description' => 'Sovassa offers UX research, journey design, UI systems, prototyping, and developer handover for websites and products.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Design problems usually show up as confusion, not as a request for a new colour.',
		'challenges' => array(
			array('title' => 'People cannot tell what to do', 'text' => 'The page is full and the primary action is still a guess.'),
			array('title' => 'Every screen was designed alone', 'text' => 'Buttons, forms, and spacing change from page to page.'),
			array('title' => 'Research is a slide, not an input', 'text' => 'Interviews happened, and the interface did not change because of them.'),
			array('title' => 'Engineering receives pictures', 'text' => 'States, errors, and empty views were never drawn, so they are invented in code.'),
		),
		'delivers' => array(
			array('title' => 'Research and discovery', 'text' => 'Interviews, a review of the current experience, and the jobs the interface must support.'),
			array('title' => 'UX architecture', 'text' => 'Sitemaps, flows, and the sequence of a task from arrival to completion.'),
			array('title' => 'UI design', 'text' => 'Screens and a small system of type, colour, and components your brand can live in.'),
			array('title' => 'Prototype and handover', 'text' => 'A clickable path for review, plus notes engineering can implement without a meeting for every pixel.'),
		),
		'capabilities' => array('Stakeholder interviews', 'Journey mapping', 'Wireframes', 'Visual design', 'Component documentation', 'Design QA against the build'),
		'stack' => array('Figma', 'Prototypes', 'Design tokens', 'Content outlines', 'Accessibility checks'),
		'process' => array(
			array('title' => 'Listen', 'text' => 'Talk to the people who sell, support, and use the product.'),
			array('title' => 'Structure', 'text' => 'Decide the flows before decorating them.'),
			array('title' => 'Design', 'text' => 'Build a system, then apply it to the screens that carry the business.'),
			array('title' => 'Validate', 'text' => 'Review with users or the team closest to them, then adjust the handover.'),
		),
		'quality' => 'We design empty, loading, and error states on purpose. Contrast, focus, and labels are part of the interface, not a checklist at the end.',
		'related' => array('web-development', 'mobile-app-development', 'content-marketing'),
		'faq' => array(
			array('q' => 'Can you design without building?', 'a' => 'Yes. The handover is written so another engineering team can implement it. We prefer to stay close to the build when the product is still changing.'),
			array('q' => 'Do you follow an existing brand?', 'a' => 'Yes. We will extend it into a working interface system, and we will flag the parts of the brand that do not survive on a screen.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'seo' => array(
		'layout' => 'service', 'pillar' => 'market', 'wp_title' => 'SEO Services', 'nav_label' => 'SEO',
		'title' => 'Search visibility that matches the work you want.',
		'eyebrow' => 'Market',
		'card' => 'Technical, on-page, content, and local SEO tied to enquiries rather than traffic alone.',
		'intro' => 'We improve how a company is found for the services it actually sells, then connect that visibility to pages and enquiries you can review.',
		'meta_title' => 'SEO Services | Sovassa Technologies',
		'meta_description' => 'Sovassa provides technical SEO, on-page SEO, content strategy, and reporting for companies that want qualified organic traffic.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'SEO disappoints when it is treated as a monthly bundle of tasks instead of a map of demand.',
		'challenges' => array(
			array('title' => 'The site targets nobody in particular', 'text' => 'Important services share one vague page, so search has nothing specific to rank.'),
			array('title' => 'Technical debt blocks good pages', 'text' => 'Titles, indexation, speed, and internal links were never owned.'),
			array('title' => 'Content is disconnected from sales', 'text' => 'Articles exist, and the service pages are still thin.'),
			array('title' => 'Reporting is a traffic chart', 'text' => 'Nobody can tell whether organic visitors became conversations.'),
		),
		'delivers' => array(
			array('title' => 'Technical SEO', 'text' => 'Crawl, indexation, templates, and the issues that stop good pages from being seen.'),
			array('title' => 'On-page SEO', 'text' => 'Titles, structure, and internal links that match the language of a search.'),
			array('title' => 'Content SEO', 'text' => 'Pages and articles planned around questions buyers already ask.'),
			array('title' => 'Local and ecommerce SEO', 'text' => 'Location or catalogue patterns when the business genuinely depends on them.'),
		),
		'capabilities' => array('Search demand review', 'Technical audit', 'Page recommendations', 'Content roadmap', 'Internal linking', 'Monthly reporting tied to enquiries'),
		'stack' => array('Search Console', 'Analytics', 'Crawling tools', 'WordPress or custom CMS', 'Content briefs'),
		'process' => array(
			array('title' => 'Audit', 'text' => 'Read the site, the queries, and the pages that should be earning attention.'),
			array('title' => 'Roadmap', 'text' => 'Sequence technical fixes, page improvements, and new content.'),
			array('title' => 'Execute', 'text' => 'Change the site and publish against that sequence.'),
			array('title' => 'Report', 'text' => 'Show movement in visibility and in the enquiries those pages support.'),
		),
		'quality' => 'We do not promise a ranking position. We do promise a readable plan, changes you can see on the site, and reporting that a non-specialist can question.',
		'related' => array('content-marketing', 'web-development', 'digital-marketing'),
		'faq' => array(
			array('q' => 'How long before SEO shows anything?', 'a' => 'Technical and on-page fixes can change what search engines see within weeks. New pages usually need longer. We will separate those timelines in the roadmap instead of offering one number.'),
			array('q' => 'Do you write the content?', 'a' => 'Yes, with content marketing, or we can brief your team. The SEO plan is weaker if nobody owns the words.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'digital-marketing' => array(
		'layout' => 'service', 'pillar' => 'market', 'wp_title' => 'Digital Marketing', 'nav_label' => 'Digital Marketing',
		'title' => 'Marketing planned across the channels you actually use.',
		'eyebrow' => 'Market',
		'card' => 'Strategy, campaigns, and reporting that connect search, content, and paid media.',
		'intro' => 'We plan and run digital marketing as a system: the message, the page it lands on, and the way the team follows up.',
		'meta_title' => 'Digital Marketing Services | Sovassa Technologies',
		'meta_description' => 'Sovassa plans and runs integrated digital marketing across SEO, content, social, and paid media, with reporting your team can use.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Growth stalls when each channel has a vendor and nobody owns the offer.',
		'challenges' => array(
			array('title' => 'Channels disagree', 'text' => 'Ads, social, and the website describe three versions of the company.'),
			array('title' => 'Activity replaces a goal', 'text' => 'The calendar is full and the pipeline is not.'),
			array('title' => 'Landing pages are an afterthought', 'text' => 'Spend sends people to a homepage that was not written for them.'),
			array('title' => 'Nobody can see the whole month', 'text' => 'Reports arrive in different formats and never meet.'),
		),
		'delivers' => array(
			array('title' => 'Marketing strategy', 'text' => 'Audience, offer, channels, and the metric that will judge the quarter.'),
			array('title' => 'Campaign execution', 'text' => 'Search, social, content, and paid work launched against that plan.'),
			array('title' => 'Page and message alignment', 'text' => 'The thing a person clicks and the page they reach say the same thing.'),
			array('title' => 'Analytics and optimization', 'text' => 'A shared view of what to keep, change, or stop.'),
		),
		'capabilities' => array('Channel planning', 'Offer messaging', 'Campaign coordination', 'Landing page briefs', 'Tracking review', 'Monthly decision notes'),
		'stack' => array('Analytics', 'Search and social ads', 'SEO tools', 'CRM or inbox handoff', 'Content calendar'),
		'process' => array(
			array('title' => 'Research', 'text' => 'Look at the current funnel, the sales conversations, and the channels already in motion.'),
			array('title' => 'Plan', 'text' => 'Choose a small set of bets instead of a presence on everything.'),
			array('title' => 'Execute', 'text' => 'Launch the work with the pages and tracking it depends on.'),
			array('title' => 'Optimize', 'text' => 'Change creative, pages, or spend based on what the month showed.'),
		),
		'quality' => 'Integrated means shared goals, not a longer slide. If a channel does not have a job, we recommend leaving it out.',
		'related' => array('seo', 'google-ads', 'content-marketing'),
		'offers' => array(
			array('title' => 'SEO', 'text' => 'Technical, on-page, and content work tied to the services you sell.', 'slug' => 'seo'),
			array('title' => 'Content marketing', 'text' => 'Pages and articles that explain the offer and support the sales conversation.', 'slug' => 'content-marketing'),
			array('title' => 'Social media marketing', 'text' => 'Strategy, creative, and community when social earns a place in the plan.', 'slug' => 'social-media-marketing'),
			array('title' => 'Paid marketing', 'text' => 'Search and paid social pointed at a page that continues the promise.', 'slug' => 'google-ads'),
		),
		'faq' => array(
			array('q' => 'Do we have to buy every channel?', 'a' => 'No. The strategy is allowed to recommend one or two. Adding channels is a later decision, not a package.'),
			array('q' => 'Will you work with our internal team?', 'a' => 'Yes. We can plan and review while your team publishes, or run execution with your team in the reviews.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'social-media-marketing' => array(
		'layout' => 'service', 'pillar' => 'market', 'wp_title' => 'Social Media Marketing', 'nav_label' => 'Social Media',
		'title' => 'Social presence with a point of view and a next step.',
		'eyebrow' => 'Market',
		'card' => 'Strategy, creative, community, and paid social when it earns a place.',
		'intro' => 'We plan social marketing around the audiences and platforms that can actually move your business, then produce the work and report on it.',
		'meta_title' => 'Social Media Marketing | Sovassa Technologies',
		'meta_description' => 'Sovassa plans social strategy, content, community activity, and paid social for companies that want a consistent presence.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Social becomes a chore when every week starts from a blank post.',
		'challenges' => array(
			array('title' => 'No content pillars', 'text' => 'Posts swing between announcements and ideas nobody asked for.'),
			array('title' => 'Creative is inconsistent', 'text' => 'The feed does not look or sound like the website.'),
			array('title' => 'Community is an unread inbox', 'text' => 'Comments and messages wait until they are awkward.'),
			array('title' => 'Paid social has no landing path', 'text' => 'Boosted posts send people nowhere in particular.'),
		),
		'delivers' => array(
			array('title' => 'Platform choice', 'text' => 'A short list of networks worth the team’s attention.'),
			array('title' => 'Content pillars', 'text' => 'The repeating themes that make a month easier to plan.'),
			array('title' => 'Creative production', 'text' => 'Posts and simple assets that match the brand and the offer.'),
			array('title' => 'Paid social, when useful', 'text' => 'Campaigns aimed at a defined audience and a page that can receive them.'),
		),
		'capabilities' => array('Channel strategy', 'Content planning', 'Creative direction', 'Community guidelines', 'Paid social setup', 'Monthly reporting'),
		'stack' => array('Organic social', 'Meta ads', 'Design tools', 'Scheduling', 'Analytics'),
		'process' => array(
			array('title' => 'Choose the room', 'text' => 'Pick platforms your buyers already use.'),
			array('title' => 'Set the pillars', 'text' => 'Agree what you will talk about, and what you will ignore.'),
			array('title' => 'Publish and respond', 'text' => 'Ship the work and give community a named owner.'),
			array('title' => 'Review', 'text' => 'Keep the themes that earn attention or conversations, and drop the rest.'),
		),
		'quality' => 'We would rather run two platforms well than six poorly. Paid social is recommended when there is an audience and a destination, not as a default add-on.',
		'related' => array('content-marketing', 'digital-marketing', 'google-ads'),
		'faq' => array(
			array('q' => 'Will you manage comments?', 'a' => 'We can define the rules and handle an agreed window. Sensitive replies should still have a person inside your company who can speak for it.'),
			array('q' => 'Do you need a designer on every post?', 'a' => 'No. A small system of layouts is usually enough. Bespoke creative is reserved for campaigns.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'google-ads' => array(
		'layout' => 'service', 'pillar' => 'market', 'wp_title' => 'Google Ads / PPC', 'nav_label' => 'Google Ads',
		'title' => 'Paid search that sends people to a page ready for them.',
		'eyebrow' => 'Market',
		'card' => 'Account structure, keywords, ads, tracking, and the landing pages they depend on.',
		'intro' => 'We plan and manage Google Ads for companies that want qualified visits, with the search terms, the ads, and the landing page treated as one system.',
		'meta_title' => 'Google Ads and PPC | Sovassa Technologies',
		'meta_description' => 'Sovassa manages Google Ads and paid search, including account structure, creative, conversion tracking, and landing page alignment.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Paid acquisition wastes money in a few repeatable ways.',
		'challenges' => array(
			array('title' => 'The account grew without a structure', 'text' => 'Campaigns overlap, and nobody can tell which offer is working.'),
			array('title' => 'Keywords and intent are mixed', 'text' => 'Research queries and buying queries share an ad and a budget.'),
			array('title' => 'The landing page is generic', 'text' => 'The click promised something the page does not continue.'),
			array('title' => 'Conversions are guessed', 'text' => 'Form fills, calls, and junk leads are counted as the same success.'),
		),
		'delivers' => array(
			array('title' => 'Account structure', 'text' => 'Campaigns grouped by offer, intent, and the page that should receive them.'),
			array('title' => 'Keyword and audience strategy', 'text' => 'What to bid on, what to exclude, and how broad to be at the start.'),
			array('title' => 'Ads and landing alignment', 'text' => 'Creative that matches a page written for the same promise.'),
			array('title' => 'Tracking and reporting', 'text' => 'Conversion definitions your team agrees are worth paying for.'),
		),
		'capabilities' => array('Account audit', 'Campaign build', 'Ad writing', 'Negative keywords', 'Conversion tracking', 'Weekly or monthly optimization'),
		'stack' => array('Google Ads', 'Analytics', 'Tag Manager', 'Landing pages', 'Call or form tracking'),
		'process' => array(
			array('title' => 'Define a conversion', 'text' => 'Agree what a useful lead or sale looks like before spending.'),
			array('title' => 'Structure the account', 'text' => 'Separate intent so budget can move toward what works.'),
			array('title' => 'Launch carefully', 'text' => 'Start with the terms and pages you can stand behind.'),
			array('title' => 'Optimize in public', 'text' => 'Change queries, ads, and pages with a note about why.'),
		),
		'quality' => 'We will not scale spend to hide a weak page. Tracking is set up before we judge a campaign, and we would rather pause a muddy conversion than celebrate it.',
		'related' => array('seo', 'digital-marketing', 'web-development'),
		'faq' => array(
			array('q' => 'Do you guarantee a cost per lead?', 'a' => 'No. We can forecast a test budget and a range once we see the account and the offer. A guarantee before that is a guess.'),
			array('q' => 'Who owns the ad account?', 'a' => 'You do. We work inside an account your company controls.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'content-marketing' => array(
		'layout' => 'service', 'pillar' => 'market', 'wp_title' => 'Content Marketing', 'nav_label' => 'Content Marketing',
		'title' => 'Content that makes the website and the sales conversation clearer.',
		'eyebrow' => 'Market',
		'card' => 'Strategy, website copy, thought leadership, and a way to reuse what you publish.',
		'intro' => 'We plan and produce content that supports a service page, a launch, or a question your team is tired of answering from scratch.',
		'meta_title' => 'Content Marketing | Sovassa Technologies',
		'meta_description' => 'Sovassa plans and produces SEO content, website copy, and thought leadership, with a workflow for distribution and measurement.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Content programs stall when publishing is separated from the pages that sell.',
		'challenges' => array(
			array('title' => 'The website is hard to quote', 'text' => 'Sales rewrites the offer because the site never quite says it.'),
			array('title' => 'Topics are chosen by habit', 'text' => 'The blog reflects what was easy to write, not what buyers ask.'),
			array('title' => 'Nothing is reused', 'text' => 'A strong explanation is published once and then forgotten.'),
			array('title' => 'Success is a publish date', 'text' => 'There is no link between an article and a page, a lead, or a sales use.'),
		),
		'delivers' => array(
			array('title' => 'Content strategy', 'text' => 'Themes, formats, and the pages each piece is meant to support.'),
			array('title' => 'Website copy', 'text' => 'Service and landing language a visitor and a salesperson can both use.'),
			array('title' => 'Thought leadership', 'text' => 'Articles with a point of view, reviewed by someone who does the work.'),
			array('title' => 'Distribution', 'text' => 'A simple path from the piece to search, social, and the inbox of the sales team.'),
		),
		'capabilities' => array('Messaging workshops', 'Content briefs', 'Drafting and editing', 'SEO alignment', 'Repurposing plans', 'A light editorial calendar'),
		'stack' => array('CMS', 'Search research', 'Editorial reviews', 'Analytics', 'Social snippets'),
		'process' => array(
			array('title' => 'Collect the questions', 'text' => 'Start from sales calls, support, and the gaps on the site.'),
			array('title' => 'Choose the form', 'text' => 'A page section, an article, or a short series. Not all three by default.'),
			array('title' => 'Produce with review', 'text' => 'Draft, check the facts with your team, and publish in the CMS.'),
			array('title' => 'Measure use', 'text' => 'Look at the pages, the enquiries, and whether sales actually sends the piece.'),
		),
		'quality' => 'We write in the company’s voice after we have heard it. Claims that need proof stay out until the proof exists.',
		'related' => array('seo', 'social-media-marketing', 'ui-ux-design'),
		'faq' => array(
			array('q' => 'Who approves the words?', 'a' => 'You do. We build a review step into the workflow so a subject expert sees the draft before it is public.'),
			array('q' => 'Can you only fix the website copy?', 'a' => 'Yes. A messaging and website-copy engagement does not require a blog program.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
);
