<?php
/**
 * Services hub and service detail pages.
 *
 * @package Sovassa
 */

$service_faq_common = array(
	array(
		'q' => 'Can this service stand alone?',
		'a' => 'Yes. We will tell you if another capability would change the outcome, and you can decide whether to include it.',
	),
	array(
		'q' => 'How do we start?',
		'a' => 'Send a consultation request with the goal, the current site or product if you have one, and the timing you have in mind.',
	),
);

return array(
	'services' => array(
		'layout'           => 'services',
		'wp_title'         => 'Services',
		'nav_label'        => 'Services',
		'title'            => 'Technology and marketing, planned as one offer.',
		'eyebrow'          => 'Our services',
		'intro'            => 'Digital marketing services sit next to the build work, not in a separate catalogue. Sovassa groups the offer into Build, Market, and Grow so you can start with a service and still see how it connects to the rest of the customer journey.',
		'meta_title'       => 'Digital Marketing Services Hub | Sovassa Technologies',
		'meta_description' => 'Digital marketing services alongside web development, app development, UI and UX design, AI automation, SEO, social, and Google Ads, each with its own page.',
		'secondary_cta'    => array('label' => 'See solutions', 'url' => 'solutions'),
		'overview'         => array(
			'This page is the short version. Each service has its own URL, so the hub does not repeat the full scope.',
			'Build covers a web development company engagement, app development, UI and UX design, and AI automation. Market covers SEO, content strategy services, social, and Google search ads. If you know the outcome rather than the channel, solutions recommends a mix.',
		),
		'together'         => array(
			array('title' => 'Build', 'text' => 'The product or website a person actually uses.'),
			array('title' => 'Market', 'text' => 'The channels that bring the right people to it.'),
			array('title' => 'Grow', 'text' => 'The operating rhythm that improves both after launch.'),
		),
		'engagements'      => array(
			array('title' => 'Fixed project', 'text' => 'A defined scope, milestones, and a delivery plan for a specific piece of work.', 'points' => array('Website or product build', 'Design system', 'Campaign launch', 'Migration')),
			array('title' => 'Monthly retainer', 'text' => 'Ongoing improvement when priorities shift and the work should not restart every month.', 'points' => array('SEO', 'Content', 'Paid media', 'Product improvements')),
			array('title' => 'Flexible support', 'text' => 'A smaller block of time for consulting, fixes, or a question that does not need a full project.', 'points' => array('Advisory', 'QA and fixes', 'Tracking setup', 'Reviews')),
		),
		'faq'              => array(
			array('q' => 'What services does Sovassa offer?', 'a' => 'Build covers web development, mobile apps, AI and automation, and UI/UX design. Market covers SEO, digital marketing, social media, Google Ads, and content. Grow covers packaged solutions that combine those services around a business outcome.'),
			array('q' => 'What do digital marketing services include?', 'a' => 'Search, content, social, and paid media, planned against the page a person lands on. A digital marketing service provider engagement can be one channel or a mix. We will say when a neighbouring service, such as the website itself, would change the result.'),
			array('q' => 'Can you combine website and marketing work?', 'a' => 'Yes. That is the reason the company is structured this way. Shared goals keep the page, the offer, and the campaign from drifting apart.'),
			array('q' => 'Which platforms do you use?', 'a' => 'The Technologies page lists the stack we actually plan around, including modern JavaScript, PHP and WordPress, mobile frameworks, cloud hosting, and common analytics tools. We choose the stack for the job rather than forcing one platform.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'web-development' => array(
		'layout' => 'service', 'pillar' => 'build', 'wp_title' => 'Web Development', 'nav_label' => 'Web Development',
		'title' => 'Websites and web applications built around a next step.',
		'eyebrow' => 'Build',
		'card' => 'Marketing sites, portals, dashboards, and web apps your team can keep using.',
		'intro' => 'If you need a web development company, the useful question is what the site must change. Sovassa provides website development services and web development services for marketing sites, portals, dashboards, and applications the team can keep editing.',
		'detail' => array(
			'The work covers the structure, the interface, and the way the team will edit the site after launch. A theme with the logo swapped is not the job. The page has to say what you sell, the form has to reach a person, and the next template has to have an obvious place to live.',
			'The same engagement includes a redesign when the current site can no longer be edited, and a web application when the job is a logged-in tool rather than a brochure. The timeline depends on how many templates are new and whether the words already exist. We review in slices, so a wrong direction shows up before the whole build is committed.',
			'A professional-services firm is a common version of this brief: the site lists departments, and a visitor cannot tell which offer to enquire about. The fix is a page per offer, a form that reaches the right person, and an editor who can change the words without a developer. The handover is that editor, not a folder of files.',
		),
		'industry' => 'industries/professional-services',
		'meta_title' => 'Web Development Company Services | Sovassa Technologies',
		'meta_description' => 'A web development company for marketing sites, portals, and web apps. Website development services include a handover your team can keep editing after launch.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Most web projects stall for reasons that are not the framework.',
		'challenges' => array(
			array('title' => 'The site no longer matches the offer', 'text' => 'Pages were added over years. A visitor cannot tell what you sell or who it is for.'),
			array('title' => 'Editing depends on a developer', 'text' => 'Small copy changes wait in a queue, so the site falls behind the sales conversation.'),
			array('title' => 'The form does not reach the team', 'text' => 'Enquiries arrive somewhere nobody owns, and follow-up is improvised.'),
			array('title' => 'Performance and structure were deferred', 'text' => 'The site looks finished and still feels slow, fragile, or impossible to extend.'),
		),
		'delivers' => array(
			array('title' => 'Marketing websites', 'text' => 'Service, industry, and campaign pages with a path to enquire.'),
			array('title' => 'Web applications', 'text' => 'Authenticated tools, portals, and workflows with a defined set of users.'),
			array('title' => 'Dashboards', 'text' => 'Internal views of the numbers and tasks a team already chases in spreadsheets.'),
			array('title' => 'Content systems', 'text' => 'WordPress or a headless CMS, chosen for who will edit the site after launch.'),
		),
		'capabilities' => array('Information architecture', 'Responsive interface development', 'CMS setup and editor training', 'Forms and basic integrations', 'Performance and accessibility passes', 'Launch and handover notes'),
		'stack' => array('WordPress', 'PHP', 'React', 'Next.js', 'Laravel', 'Headless CMS'),
		'offers' => array(
			array('title' => 'Custom websites', 'text' => 'A site designed around the offer, not a theme with the logo swapped.'),
			array('title' => 'WordPress', 'text' => 'Marketing and content sites the team can edit after launch.'),
			array('title' => 'Webflow', 'text' => 'Designed pages with a visual editor when that is the right publishing model.'),
			array('title' => 'Shopify', 'text' => 'A store structured around collections, checkout, and the campaigns that send people there.'),
			array('title' => 'eCommerce', 'text' => 'Catalogue, merchandising, and the pages a buyer needs before they pay.'),
			array('title' => 'Web applications', 'text' => 'Logged-in tools, portals, and workflows with a defined set of users.'),
			array('title' => 'Landing pages', 'text' => 'A page written for one campaign or one offer, with a single next step.'),
			array('title' => 'Website redesign', 'text' => 'A new structure and interface for a site that no longer matches the business.'),
			array('title' => 'Website maintenance', 'text' => 'Updates, fixes, and small improvements after the site is live.'),
		),
		'process' => array(
			array('title' => 'Discover', 'text' => 'Map the audience, the pages that matter, and the systems the site must talk to.'),
			array('title' => 'Shape', 'text' => 'Agree the sitemap, the editing model, and the interactions worth designing in detail.'),
			array('title' => 'Build', 'text' => 'Develop in reviewable slices, with content and tracking included rather than bolted on.'),
			array('title' => 'Launch', 'text' => 'Check quality, speed, and the handover your team will use the following week.'),
		),
		'quality' => 'We treat performance, security updates, editor permissions, and a sensible content model as part of the build. Scalability means the next page or integration has an obvious place to live.',
		'related' => array('ui-ux-design', 'seo', 'content-marketing'),
		'faq' => array(
			array('q' => 'What does a web development company engagement include?', 'a' => 'Information architecture, the interface, a CMS the team can edit, forms, a performance pass, and launch notes. It can also mean a redesign or a web application when that is the real job.'),
			array('q' => 'Do you build in WordPress?', 'a' => 'Yes, when editing and marketing pages are the priority. We use a custom front end when the product is really an application. The choice is part of discovery, not a default.'),
			array('q' => 'Can you improve a site we already have?', 'a' => 'Often. We will say if a rebuild is the honest recommendation after looking at the theme, the content, and the editor experience.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'mobile-app-development' => array(
		'layout' => 'service', 'pillar' => 'build', 'wp_title' => 'Mobile App Development', 'nav_label' => 'Mobile Apps',
		'title' => 'Mobile products with a reason to exist on a phone.',
		'eyebrow' => 'Build',
		'card' => 'iOS, Android, and cross-platform apps planned around a job to be done.',
		'intro' => 'App development starts with the job a phone should do. Mobile application development at Sovassa covers iOS, Android, and cross-platform builds when that job is real, including the interface, device QA, and the first store release.',
		'detail' => array(
			'An app brief that is only a feature list is not ready to build. We name the repeated task, the person who does it, and the smallest release that can teach the team something. Native and cross-platform are a choice about that product, not a habit.',
			'The build then includes the accounts, the data the phone must reach, and the month after the store approves the build. Release support is part of the scope. We do not treat submission as the end of the engagement.',
			'Software and startup teams often arrive with a deck and no product path on a phone. The work in that case is one job, shipped small enough to learn from, with a plan for the fixes that show up after people actually use it. A second platform waits until the first job is clear.',
		),
		'industry' => 'industries/software-and-startups',
		'meta_title' => 'App Development for iOS and Android | Sovassa Tech',
		'meta_description' => 'App development for iOS, Android, and cross-platform products. Mobile application development includes UX, device QA, and the first public store release.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Mobile work fails when the app is a smaller copy of a website nobody asked to carry in a pocket.',
		'challenges' => array(
			array('title' => 'The job is unclear', 'text' => 'Stakeholders want an app before they can name the repeated task it should remove.'),
			array('title' => 'iOS and Android drift apart', 'text' => 'Two codebases, two backlogs, and a design that fits neither platform well.'),
			array('title' => 'Accounts and data are an afterthought', 'text' => 'Sign-in, permissions, and offline behaviour appear late and reshape the product.'),
			array('title' => 'Release is treated as the end', 'text' => 'Store review, crash reporting, and the first month of fixes were never in the plan.'),
		),
		'delivers' => array(
			array('title' => 'Product definition', 'text' => 'The journeys, roles, and release slice that deserve a first version.'),
			array('title' => 'iOS and Android', 'text' => 'Native or cross-platform implementation, chosen for the product rather than habit.'),
			array('title' => 'Integrations', 'text' => 'APIs, notifications, and the admin tools the team needs to operate the app.'),
			array('title' => 'Release support', 'text' => 'Store submission, QA notes, and a plan for the issues that show up after launch.'),
		),
		'capabilities' => array('Journey mapping', 'Interface design for mobile', 'Cross-platform or native build', 'API integration', 'QA on real devices', 'Store release support'),
		'stack' => array('Swift', 'Kotlin', 'Flutter', 'React Native', 'REST APIs', 'Push notifications'),
		'offers' => array(
			array('title' => 'iOS', 'text' => 'Native iPhone and iPad apps when platform behaviour is part of the product.'),
			array('title' => 'Android', 'text' => 'Native Android apps for the devices and versions your users actually have.'),
			array('title' => 'Flutter', 'text' => 'One codebase for iOS and Android when the product can share most of the interface.'),
			array('title' => 'React Native', 'text' => 'Cross-platform apps when the team already works in the JavaScript ecosystem.'),
			array('title' => 'Cross-platform', 'text' => 'A shared app where the first release does not need two separate codebases.'),
			array('title' => 'MVP', 'text' => 'The smallest release that lets real users complete the core job.'),
			array('title' => 'Enterprise apps', 'text' => 'Apps with roles, permissions, and the systems a larger organisation already runs.'),
			array('title' => 'App UI/UX', 'text' => 'Research, journeys, and interface design before or alongside the build.'),
			array('title' => 'App maintenance', 'text' => 'Fixes, store updates, and the first months after release.'),
			array('title' => 'App modernization', 'text' => 'A planned rebuild or upgrade of an app that is hard to change or no longer fits the platform.'),
		),
		'process' => array(
			array('title' => 'Frame the product', 'text' => 'Decide who the app is for and which task the first release must complete.'),
			array('title' => 'Design the journeys', 'text' => 'Prototype the critical paths before engineering commits to them.'),
			array('title' => 'Build in slices', 'text' => 'Ship reviewable increments with tracking and empty states included.'),
			array('title' => 'Release and watch', 'text' => 'Prepare store assets, test, and leave a clear path for the first fixes.'),
		),
		'quality' => 'QA, permission handling, and a basic security review of accounts and data are part of the engagement. We do not treat the store listing as someone else’s problem.',
		'related' => array('ui-ux-design', 'web-development', 'ai-automation'),
		'faq' => array(
			array('q' => 'What does app development include?', 'a' => 'The job the phone should do, the journeys, the build for iOS, Android, or both, and support through the first store release. It also covers the accounts and data that release depends on.'),
			array('q' => 'Should we build native or cross-platform?', 'a' => 'Cross-platform is often right for a shared product with a modest device-specific surface. Native is right when platform behaviour is the product. We recommend one after discovery.'),
			array('q' => 'Do you design the app as well?', 'a' => 'Yes. Interface and engineering can be scoped together or alongside an existing design, as long as the flows are allowed to change when they do not hold up.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'ai-automation' => array(
		'layout' => 'service', 'pillar' => 'build', 'wp_title' => 'AI & Automation', 'nav_label' => 'AI & Automation',
		'title' => 'Practical AI and automation for work you already do.',
		'eyebrow' => 'Build',
		'card' => 'Workflows, assistants, and integrations with a human check and a clear boundary.',
		'intro' => 'What is AI automation? It is a repeated handoff turned into a workflow, with a person still checking the exceptions. Sovassa designs that AI automation only when the steps are already understood, and leaves it alone when the process is still changing every week.',
		'detail' => array(
			'The first step is a map: who receives the work, what done means, and which system should hold the record. The workflow then covers the repeated, low-judgement step. The exceptions stay with a person. A workflow that freezes a messy process is not a success.',
			'Data boundaries are part of the design. We name which documents or records the workflow may use, and what it must not see. If the output cannot be checked, we do not ship it. Rollback is included, so a bad change can be undone without a rescue project.',
			'Real estate teams often feel this as leads arriving faster than follow-up. In that setting the useful version is the repeated handoff from the form into the tool the team already uses, with a person still responsible for the conversation. It is not a chatbot that invents an answer about a listing.',
			'You describe the step as it happens today, including the exceptions a person still has to catch. We write down the systems involved, what “done” looks like, and how a mistake is reversed. A pilot runs with one team before anyone talks about a second department. If the people doing the job do not trust the output after that pilot, we stop. Expanding a workflow nobody will use is not a later phase. It is a reason to leave the work as it was.',
		),
		'industry' => 'industries/real-estate',
		'meta_title' => 'AI Automation for Repeated Work | Sovassa Technologies',
		'meta_description' => 'What is AI automation? A repeated handoff turned into a workflow with a human check. Sovassa designs AI automation with a data boundary and a way to undo it.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'The opportunity is rarely “add AI”. It is a handoff that wastes the same hour every day.',
		'challenges' => array(
			array('title' => 'Work lives in inboxes', 'text' => 'Requests, briefs, and status updates are retyped between tools.'),
			array('title' => 'People do not trust the output', 'text' => 'A generated draft has no owner, no source, and no way to reject it.'),
			array('title' => 'Data boundaries are vague', 'text' => 'Customer or internal information might be pasted into tools nobody has reviewed.'),
			array('title' => 'The demo never becomes a process', 'text' => 'A prototype impresses a meeting and never reaches the team that would use it.'),
		),
		'delivers' => array(
			array('title' => 'Workflow automation', 'text' => 'Handoffs between the tools you already use, with a record of what happened.'),
			array('title' => 'Assistive drafting', 'text' => 'First drafts for support, content, or internal notes, with a person approving the send.'),
			array('title' => 'Internal knowledge tools', 'text' => 'A bounded assistant over documents you choose, not an open-ended chatbot.'),
			array('title' => 'Product features', 'text' => 'An AI capability inside a web or mobile product, scoped like any other feature.'),
		),
		'capabilities' => array('Process mapping', 'Integration design', 'Prompt and workflow setup', 'Human review steps', 'Access and data boundaries', 'A rollback if the workflow misbehaves'),
		'stack' => array('Workflow tools', 'API integrations', 'LLM APIs', 'Python', 'Web apps', 'Analytics events'),
		'process' => array(
			array('title' => 'Find the repeated task', 'text' => 'Watch the work long enough to name the step worth automating.'),
			array('title' => 'Bound the data', 'text' => 'Decide what the system may read, store, and show, and what it must not.'),
			array('title' => 'Build the smallest loop', 'text' => 'A workflow one team can run, with a way to correct mistakes.'),
			array('title' => 'Review before you expand', 'text' => 'Keep it only if the people doing the job trust it.'),
		),
		'quality' => 'Responsible implementation here means a named owner, a data boundary, and a way to turn the workflow off. We do not ship an assistant that nobody is accountable for.',
		'related' => array('web-development', 'digital-marketing', 'solutions'),
		'faq' => array(
			array('q' => 'What is AI automation, in a project rather than a slogan?', 'a' => 'A repeated step the team can already describe, moved into a workflow with a human check and a way to undo it. If the process is still changing every week, that workflow waits.'),
			array('q' => 'Do you train custom models?', 'a' => 'Not as a default. Most useful work is a workflow, a retrieval boundary, or a product feature on top of an existing model. Custom training is a different project and we will say if it is unnecessary.'),
			array('q' => 'Is our content sent to a third party?', 'a' => 'Only if we agree that in the scope. The design includes which provider is used and what is allowed to leave your systems.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'ui-ux-design' => array(
		'layout' => 'service', 'pillar' => 'build', 'wp_title' => 'UI/UX Design', 'nav_label' => 'UI/UX Design',
		'title' => 'Design that makes the next step obvious.',
		'eyebrow' => 'Build',
		'card' => 'Research, journeys, interface design, and a handover engineering can build.',
		'intro' => 'UI and UX design is the research, the journey, and the interface a person can finish. UI UX development services add the handover engineering can build, so the file is not the end of the work.',
		'detail' => array(
			'The engagement starts with the decision the screen has to support. We interview the people who sell or operate the product, map the path, and design the states that usually get skipped: empty, error, and the moment someone is unsure. Visual polish comes after that path holds.',
			'The handover includes component notes and a review against the build. You can hire the design alone. We will say when staying close to engineering would stop the interface from drifting once development starts.',
			'Fintech and other products that ask for money or data need the next step visible before the form. The design here means the journey, the limit of the product, and screens that do not hide a fee or a permission in a policy PDF. We do not invent those claims. Your team supplies them, and the interface has to show them.',
			'You bring the people who sell or support the product, and any rule the interface cannot invent: a price, a limit, a permission, a brand constraint. We bring the journeys and the states that usually get skipped, including empty, error, and the moment someone hesitates. Reviews cover a small set of flows, not every screen at once. If a comment changes the job a screen is doing, that is a change of scope, and we say so before redrawing the rest. A folder of pictures without those states is not something engineering can build from without guessing.',
		),
		'industry' => 'industries/fintech',
		'meta_title' => 'Product UI and UX Design Services | Sovassa Technologies',
		'meta_description' => 'UI and UX design for websites and products, plus UI UX development services with a handover engineering can build for web and mobile screens from the start.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Design problems usually show up as confusion, not as a request for a new colour.',
		'challenges' => array(
			array('title' => 'People cannot tell what to do', 'text' => 'The page is full and the primary action is still a guess.'),
			array('title' => 'Every screen was designed alone', 'text' => 'Buttons, forms, and spacing change from page to page.'),
			array('title' => 'Research is a slide, not an input', 'text' => 'Interviews happened, and the interface did not change because of them.'),
			array('title' => 'Engineering receives pictures', 'text' => 'States, errors, and empty views were never drawn, so they are invented in code.'),
		),
		'delivers' => array(
			array('title' => 'Research and discovery', 'text' => 'Interviews, a review of the current experience, and the jobs the interface must support.'),
			array('title' => 'UX architecture', 'text' => 'Sitemaps, flows, and the sequence of a task from arrival to completion.'),
			array('title' => 'UI design', 'text' => 'Screens and a small system of type, colour, and components your brand can live in.'),
			array('title' => 'Prototype and handover', 'text' => 'A clickable path for review, plus notes engineering can implement without a meeting for every pixel.'),
		),
		'capabilities' => array('Stakeholder interviews', 'Journey mapping', 'Wireframes', 'Visual design', 'Component documentation', 'Design QA against the build'),
		'stack' => array('Figma', 'Prototypes', 'Design tokens', 'Content outlines', 'Accessibility checks'),
		'process' => array(
			array('title' => 'Listen', 'text' => 'Talk to the people who sell, support, and use the product.'),
			array('title' => 'Structure', 'text' => 'Decide the flows before decorating them.'),
			array('title' => 'Design', 'text' => 'Build a system, then apply it to the screens that carry the business.'),
			array('title' => 'Validate', 'text' => 'Review with users or the team closest to them, then adjust the handover.'),
		),
		'quality' => 'We design empty, loading, and error states on purpose. Contrast, focus, and labels are part of the interface, not a checklist at the end. The handover names the components and the places a later screen should reuse them, so the next page does not start from a blank frame.',
		'related' => array('web-development', 'mobile-app-development', 'content-marketing'),
		'faq' => array(
			array('q' => 'What does UI and UX design include?', 'a' => 'Research, the journey, the interface, and a handover engineering can build. When you also want the screens produced, not only a file of mockups, that handover stays in the same engagement.'),
			array('q' => 'Can you design without building?', 'a' => 'Yes. The handover is written so another engineering team can implement it. We prefer to stay close to the build when the product is still changing.'),
			array('q' => 'Do you follow an existing brand?', 'a' => 'Yes. We will extend it into a working interface system, and we will flag the parts of the brand that do not survive on a screen.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'seo' => array(
		'layout' => 'service', 'pillar' => 'market', 'wp_title' => 'SEO Services', 'nav_label' => 'SEO',
		'title' => 'Search visibility that matches the work you want.',
		'eyebrow' => 'Market',
		'card' => 'Technical, on-page, content, and local SEO tied to enquiries rather than traffic alone.',
		'intro' => 'Sovassa is an SEO company in Zirakpur, and we also work with clients elsewhere. As an SEO service provider, the work is technical cleanup, on-page structure, and pages written for the services you actually sell. An SEO company is useful only when those pages can receive an enquiry.',
		'detail' => array(
			'The engagement starts with the queries a buyer would type and the pages that should answer them. Titles, internal links, and indexation are fixed where they block those pages. New writing follows the same map, instead of a separate blog that never meets the offer.',
			'Reporting looks at enquiries and the pages that assisted them, not a traffic chart on its own. We do not promise a ranking position. We do promise a plan you can read, changes you can see on the site, and a split between fixes that move quickly and pages that need longer.',
			'For a firm that sells expertise, the engagement pairs the technical cleanup with service pages written in the language buyers already use. A local office does not mean every page is about that city. Location is included when the business actually serves that place, and left out when it would make a thin page.',
			'You will need someone who can confirm what the company actually sells, and access to the site and the search account. We will not invent a service page for a query that does not match an offer. The first month is usually the fixes that stop good pages from being seen, plus a short list of pages to write or rewrite. Later months follow that list. A report that only shows visits, with no note about which page should change next, is not the reporting we send.',
		),
		'industry' => 'industries/professional-services',
		'meta_title' => 'SEO Company in Zirakpur, India | Sovassa Technologies',
		'meta_description' => 'Sovassa is an SEO company in Zirakpur and an SEO service provider for clients elsewhere. Technical and on-page SEO tied to enquiries, not traffic alone.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'SEO disappoints when it is treated as a monthly bundle of tasks instead of a map of demand.',
		'challenges' => array(
			array('title' => 'The site targets nobody in particular', 'text' => 'Important services share one vague page, so search has nothing specific to rank.'),
			array('title' => 'Technical debt blocks good pages', 'text' => 'Titles, indexation, speed, and internal links were never owned.'),
			array('title' => 'Content is disconnected from sales', 'text' => 'Articles exist, and the service pages are still thin.'),
			array('title' => 'Reporting is a traffic chart', 'text' => 'Nobody can tell whether organic visitors became conversations.'),
		),
		'delivers' => array(
			array('title' => 'Technical SEO', 'text' => 'Crawl, indexation, templates, and the issues that stop good pages from being seen.'),
			array('title' => 'On-page SEO', 'text' => 'Titles, structure, and internal links that match the language of a search.'),
			array('title' => 'Content SEO', 'text' => 'Pages and articles planned around questions buyers already ask.'),
			array('title' => 'Local and ecommerce SEO', 'text' => 'Location or catalogue patterns when the business genuinely depends on them.'),
		),
		'capabilities' => array('Search demand review', 'Technical audit', 'Page recommendations', 'Content roadmap', 'Internal linking', 'Monthly reporting tied to enquiries'),
		'stack' => array('Search Console', 'Analytics', 'Crawling tools', 'WordPress or custom CMS', 'Content briefs'),
		'process' => array(
			array('title' => 'Audit', 'text' => 'Read the site, the queries, and the pages that should be earning attention.'),
			array('title' => 'Roadmap', 'text' => 'Sequence technical fixes, page improvements, and new content.'),
			array('title' => 'Execute', 'text' => 'Change the site and publish against that sequence.'),
			array('title' => 'Report', 'text' => 'Show movement in visibility and in the enquiries those pages support.'),
		),
		'quality' => 'We do not promise a ranking position. We do promise a readable plan, changes you can see on the site, and reporting that a non-specialist can question. Fixes that can move quickly are separated from pages that need longer, so a quiet month is not described as a failure of the whole plan.',
		'related' => array('content-marketing', 'web-development', 'digital-marketing'),
		'faq' => array(
			array('q' => 'Do you work as an SEO company in Zirakpur?', 'a' => 'Yes. The office is in Zirakpur, and the same work is available to clients elsewhere. Local pages are written only when the business genuinely serves that place.'),
			array('q' => 'How long before SEO shows anything?', 'a' => 'Technical and on-page fixes can change what search engines see within weeks. New pages usually need longer. We will separate those timelines in the roadmap instead of offering one number.'),
			array('q' => 'Do you write the content?', 'a' => 'Yes, with content marketing, or we can brief your team. The SEO plan is weaker if nobody owns the words.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'digital-marketing' => array(
		'layout' => 'service', 'pillar' => 'market', 'wp_title' => 'Digital Marketing', 'nav_label' => 'Digital Marketing',
		'title' => 'Marketing planned across the channels you actually use.',
		'eyebrow' => 'Market',
		'card' => 'Strategy, campaigns, and reporting that connect search, content, and paid media.',
		'intro' => 'Sovassa is a digital marketing service provider for search, content, social, and paid media planned as one system. A digital marketing agency, or a digital marketing company hired channel by channel, often leaves the page behind the campaign. Digital marketing services here can still be a single channel when that is the real brief.',
		'detail' => array(
			'The plan names the offer, the audience, and the page that should receive the visit. Channels without that page are not launched to fill a calendar. Follow-up is part of the design: an enquiry needs an owner, not only a form that stores a name.',
			'A month ends with a note about what changed, what did not, and the next decision. The work is judged on that decision, not on how many assets were produced. If your team will publish, we can plan and review. If you want execution, that is scoped as its own work.',
			'Education programs are one place this shows up: many courses, and a prospective student who cannot tell which one is theirs. More ads do not fix that. The course page has to exist first. Campaigns then land on that page, not on a list of every program.',
			'The first conversation names the offer, the person who should enquire, and who replies after the form. If those three are unclear, the useful work is the message and the page, not a new channel. A monthly note then says what changed, what stayed flat, and the one decision for the next month. Adding a channel because the calendar looks empty is a recommendation we will not make. Your team can publish while we plan and review, or execution can be scoped on its own.',
		),
		'industry' => 'industries/education',
		'meta_title' => 'Digital Marketing Services Provider | Sovassa Tech',
		'meta_description' => 'A digital marketing service provider for search, content, social, and paid media. Digital marketing services stay tied to the landing page and the follow-up.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Growth stalls when each channel has a vendor and nobody owns the offer.',
		'challenges' => array(
			array('title' => 'Channels disagree', 'text' => 'Ads, social, and the website describe three versions of the company.'),
			array('title' => 'Activity replaces a goal', 'text' => 'The calendar is full and the pipeline is not.'),
			array('title' => 'Landing pages are an afterthought', 'text' => 'Spend sends people to a homepage that was not written for them.'),
			array('title' => 'Nobody can see the whole month', 'text' => 'Reports arrive in different formats and never meet.'),
		),
		'delivers' => array(
			array('title' => 'Marketing strategy', 'text' => 'Audience, offer, channels, and the metric that will judge the quarter.'),
			array('title' => 'Campaign execution', 'text' => 'Search, social, content, and paid work launched against that plan.'),
			array('title' => 'Page and message alignment', 'text' => 'The thing a person clicks and the page they reach say the same thing.'),
			array('title' => 'Analytics and optimization', 'text' => 'A shared view of what to keep, change, or stop.'),
		),
		'capabilities' => array('Channel planning', 'Offer messaging', 'Campaign coordination', 'Landing page briefs', 'Tracking review', 'Monthly decision notes'),
		'stack' => array('Analytics', 'Search and social ads', 'SEO tools', 'CRM or inbox handoff', 'Content calendar'),
		'process' => array(
			array('title' => 'Research', 'text' => 'Look at the current funnel, the sales conversations, and the channels already in motion.'),
			array('title' => 'Plan', 'text' => 'Choose a small set of bets instead of a presence on everything.'),
			array('title' => 'Execute', 'text' => 'Launch the work with the pages and tracking it depends on.'),
			array('title' => 'Optimize', 'text' => 'Change creative, pages, or spend based on what the month showed.'),
		),
		'quality' => 'Integrated means shared goals, not a longer slide. If a channel does not have a job, we recommend leaving it out.',
		'related' => array('seo', 'google-ads', 'content-marketing'),
		'offers' => array(
			array('title' => 'SEO', 'text' => 'Technical, on-page, and content work tied to the services you sell.', 'slug' => 'seo'),
			array('title' => 'Content marketing', 'text' => 'Pages and articles that explain the offer and support the sales conversation.', 'slug' => 'content-marketing'),
			array('title' => 'Social media marketing', 'text' => 'Strategy, creative, and community when social earns a place in the plan.', 'slug' => 'social-media-marketing'),
			array('title' => 'Paid marketing', 'text' => 'Search and paid social pointed at a page that continues the promise.', 'slug' => 'google-ads'),
		),
		'faq' => array(
			array('q' => 'What does a digital marketing service provider run?', 'a' => 'The channels the brief actually needs: search, content, social, paid media, or a mix. The work includes the page those channels land on, and a monthly note about what to change.'),
			array('q' => 'Do we have to buy every channel?', 'a' => 'No. The strategy is allowed to recommend one or two. Adding channels is a later decision, not a package.'),
			array('q' => 'Will you work with our internal team?', 'a' => 'Yes. We can plan and review while your team publishes, or run execution with your team in the reviews.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'social-media-marketing' => array(
		'layout' => 'service', 'pillar' => 'market', 'wp_title' => 'Social Media Marketing', 'nav_label' => 'Social Media',
		'title' => 'Social presence with a point of view and a next step.',
		'eyebrow' => 'Market',
		'card' => 'Strategy, creative, community, and paid social when it earns a place.',
		'intro' => 'What is social media marketing, for a company rather than a textbook? It is a small set of platforms, a repeating point of view, and a next step that matches the website. Sovassa plans that presence, the creative, and the replies. Paid social is added only when a page is ready to receive it.',
		'detail' => array(
			'The first decision is which rooms are worth the team’s time. Two platforms run properly beat six accounts that go quiet. Content pillars come from the offer and the questions buyers already ask, so a month does not start from a blank post.',
			'Community needs a named owner and a rule for what the company will say in public. Sensitive replies stay with someone inside the business. Creative uses a small set of layouts. A bespoke asset is for a campaign, not for every Tuesday.',
			'When the company sells expertise, the useful version is a steady explanation of the offer, close enough to the website that sales can recognise it. It is not a second brand. Professional-services firms usually need fewer posts and a clearer next step, not a presence on every network.',
			'A month has a small set of themes, a layout the team can repeat, and a named owner for replies. Sensitive comments stay with someone inside the company. Paid promotion waits until a page can receive the visit and continue the same offer. We would rather keep two networks current than open accounts that go quiet. A calendar full of posts, with no destination and no one reading the replies, is the failure mode this engagement is meant to avoid.',
		),
		'industry' => 'industries/professional-services',
		'meta_title' => 'Social Media Marketing Services | Sovassa Technologies',
		'meta_description' => 'Sovassa plans social strategy, creative, community activity, and paid social for companies that need a consistent presence tied to the same public offer.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Social becomes a chore when every week starts from a blank post.',
		'challenges' => array(
			array('title' => 'No content pillars', 'text' => 'Posts swing between announcements and ideas nobody asked for.'),
			array('title' => 'Creative is inconsistent', 'text' => 'The feed does not look or sound like the website.'),
			array('title' => 'Community is an unread inbox', 'text' => 'Comments and messages wait until they are awkward.'),
			array('title' => 'Paid social has no landing path', 'text' => 'Boosted posts send people nowhere in particular.'),
		),
		'delivers' => array(
			array('title' => 'Platform choice', 'text' => 'A short list of networks worth the team’s attention.'),
			array('title' => 'Content pillars', 'text' => 'The repeating themes that make a month easier to plan.'),
			array('title' => 'Creative production', 'text' => 'Posts and simple assets that match the brand and the offer.'),
			array('title' => 'Paid social, when useful', 'text' => 'Campaigns aimed at a defined audience and a page that can receive them.'),
		),
		'capabilities' => array('Channel strategy', 'Content planning', 'Creative direction', 'Community guidelines', 'Paid social setup', 'Monthly reporting'),
		'stack' => array('Organic social', 'Meta ads', 'Design tools', 'Scheduling', 'Analytics'),
		'process' => array(
			array('title' => 'Choose the room', 'text' => 'Pick platforms your buyers already use.'),
			array('title' => 'Set the pillars', 'text' => 'Agree what you will talk about, and what you will ignore.'),
			array('title' => 'Publish and respond', 'text' => 'Ship the work and give community a named owner.'),
			array('title' => 'Review', 'text' => 'Keep the themes that earn attention or conversations, and drop the rest.'),
		),
		'quality' => 'We would rather run two platforms well than six poorly. Paid social is recommended when there is an audience and a destination, not as a default add-on. A month is planned before it is designed, and a post that does not match the website is revised or dropped. Community rules are written down so a reply does not depend on whoever happens to see the notification.',
		'related' => array('content-marketing', 'digital-marketing', 'google-ads'),
		'faq' => array(
			array('q' => 'What should a social program change?', 'a' => 'It should make the offer easier to recognise and give a person a next step that matches the website. A full calendar with no destination is not the goal.'),
			array('q' => 'Will you manage comments?', 'a' => 'We can define the rules and handle an agreed window. Sensitive replies should still have a person inside your company who can speak for it.'),
			array('q' => 'Do you need a designer on every post?', 'a' => 'No. A small system of layouts is usually enough. Bespoke creative is reserved for campaigns.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'google-ads' => array(
		'layout' => 'service', 'pillar' => 'market', 'wp_title' => 'Google Ads / PPC', 'nav_label' => 'Google Ads',
		'title' => 'Paid search that sends people to a page ready for them.',
		'eyebrow' => 'Market',
		'card' => 'Account structure, keywords, ads, tracking, and the landing pages they depend on.',
		'intro' => 'Google search ads work when the query, the ad, and the landing page describe the same offer. Sovassa manages that system: account structure, keywords, ads, and the tracking that tells a useful enquiry from noise. Spend does not grow to hide a page that is not ready.',
		'detail' => array(
			'The account is grouped by offer and intent, so a research query and a buying query do not share one budget by accident. Negative keywords and a conversion your team agrees is real come before any judgement of the campaign. You own the ad account. We work inside it.',
			'Landing pages are part of the engagement when the current site cannot continue the promise in the ad. We will pause a muddy setup rather than report it as success. A cost per lead is a range after we see the offer, not a guarantee in the first call.',
			'Ecommerce is a typical case. Ads for a collection only help when the shelf matches the ad. If merchandising and acquisition were planned apart, the first job is the page, then the queries that should reach it. We will not point spend at a homepage that does not continue the offer.',
			'A review looks at search terms, the ads people actually saw, and whether the enquiry was one your team wanted. Junk leads are called junk. Budget moves toward the offer that produced a real conversation, and away from queries that only look busy. Creative changes when the same ad has been ignored, not on a calendar. If the useful next step is a clearer page rather than a higher bid, that is the recommendation, even when it means spending less for a while.',
		),
		'industry' => 'industries/ecommerce',
		'meta_title' => 'Google Ads and PPC Management | Sovassa Technologies',
		'meta_description' => 'Sovassa manages Google Ads and paid search, from account structure and ad copy to conversion tracking and the landing pages those paid clicks actually reach.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Paid acquisition wastes money in a few repeatable ways.',
		'challenges' => array(
			array('title' => 'The account grew without a structure', 'text' => 'Campaigns overlap, and nobody can tell which offer is working.'),
			array('title' => 'Keywords and intent are mixed', 'text' => 'Research queries and buying queries share an ad and a budget.'),
			array('title' => 'The landing page is generic', 'text' => 'The click promised something the page does not continue.'),
			array('title' => 'Conversions are guessed', 'text' => 'Form fills, calls, and junk leads are counted as the same success.'),
		),
		'delivers' => array(
			array('title' => 'Account structure', 'text' => 'Campaigns grouped by offer, intent, and the page that should receive them.'),
			array('title' => 'Keyword and audience strategy', 'text' => 'What to bid on, what to exclude, and how broad to be at the start.'),
			array('title' => 'Ads and landing alignment', 'text' => 'Creative that matches a page written for the same promise.'),
			array('title' => 'Tracking and reporting', 'text' => 'Conversion definitions your team agrees are worth paying for.'),
		),
		'capabilities' => array('Account audit', 'Campaign build', 'Ad writing', 'Negative keywords', 'Conversion tracking', 'Weekly or monthly optimization'),
		'stack' => array('Google Ads', 'Analytics', 'Tag Manager', 'Landing pages', 'Call or form tracking'),
		'process' => array(
			array('title' => 'Define a conversion', 'text' => 'Agree what a useful lead or sale looks like before spending.'),
			array('title' => 'Structure the account', 'text' => 'Separate intent so budget can move toward what works.'),
			array('title' => 'Launch carefully', 'text' => 'Start with the terms and pages you can stand behind.'),
			array('title' => 'Optimize in public', 'text' => 'Change queries, ads, and pages with a note about why.'),
		),
		'quality' => 'We will not scale spend to hide a weak page. Tracking is set up before we judge a campaign, and we would rather pause a muddy conversion than celebrate it. Search terms are reviewed often enough that a bad query does not spend for a month unnoticed. Changes to ads, queries, and pages are written down so the next review can tell what actually moved.',
		'related' => array('seo', 'digital-marketing', 'web-development'),
		'faq' => array(
			array('q' => 'When are Google search ads worth running?', 'a' => 'When the offer is clear, the landing page continues the ad, and someone owns the enquiry. A larger budget does not fix a page that says something else.'),
			array('q' => 'Do you guarantee a cost per lead?', 'a' => 'No. We can forecast a test budget and a range once we see the account and the offer. A guarantee before that is a guess.'),
			array('q' => 'Who owns the ad account?', 'a' => 'You do. We work inside an account your company controls.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
	'content-marketing' => array(
		'layout' => 'service', 'pillar' => 'market', 'wp_title' => 'Content Marketing', 'nav_label' => 'Content Marketing',
		'title' => 'Content that makes the website and the sales conversation clearer.',
		'eyebrow' => 'Market',
		'card' => 'Strategy, website copy, thought leadership, and a way to reuse what you publish.',
		'intro' => 'Content strategy services start from the questions sales already hears. Sovassa plans and writes the pages and articles that answer them. An SEO content strategy is part of that work when search is how the questions arrive, not a separate publishing calendar.',
		'detail' => array(
			'Each piece has a page to support or a conversation to shorten. Website copy, a short article, and a note sales can send may be the same point in three forms. We do not start a blog because a calendar has empty weeks.',
			'The search side of the plan names the queries, the page that should rank, and the proof the company can actually stand behind. Claims without that proof stay out. You approve the words before they are public, with a subject expert in the review.',
			'Healthcare pages are a clear example. The writing there means plain language, a next step for a patient or a referrer, and no clinical claim the organisation did not supply. Search does not override that caution. If a sentence needs a result we do not have, it does not ship.',
			'You approve the words, and a person who knows the subject sees the draft before it is public. We start from questions sales or support already hears, then choose whether the answer belongs on an existing page or in a new one. A blog post that does not point at a page the company can sell from is a later decision, not the default. The same point may also become a short note the sales team can send. Publishing on a date, with nobody using the piece, is not a result.',
		),
		'industry' => 'industries/healthcare',
		'meta_title' => 'Content Strategy Services and SEO | Sovassa Technologies',
		'meta_description' => 'Content strategy services for pages, website copy, and articles sales can use. SEO content strategy is included when those questions are also searches.',
		'crumb_parent' => array('label' => 'Services', 'slug' => 'services'),
		'challenges_intro' => 'Content programs stall when publishing is separated from the pages that sell.',
		'challenges' => array(
			array('title' => 'The website is hard to quote', 'text' => 'Sales rewrites the offer because the site never quite says it.'),
			array('title' => 'Topics are chosen by habit', 'text' => 'The blog reflects what was easy to write, not what buyers ask.'),
			array('title' => 'Nothing is reused', 'text' => 'A strong explanation is published once and then forgotten.'),
			array('title' => 'Success is a publish date', 'text' => 'There is no link between an article and a page, a lead, or a sales use.'),
		),
		'delivers' => array(
			array('title' => 'Content strategy', 'text' => 'Themes, formats, and the pages each piece is meant to support.'),
			array('title' => 'Website copy', 'text' => 'Service and landing language a visitor and a salesperson can both use.'),
			array('title' => 'Thought leadership', 'text' => 'Articles with a point of view, reviewed by someone who does the work.'),
			array('title' => 'Distribution', 'text' => 'A simple path from the piece to search, social, and the inbox of the sales team.'),
		),
		'capabilities' => array('Messaging workshops', 'Content briefs', 'Drafting and editing', 'SEO alignment', 'Repurposing plans', 'A light editorial calendar'),
		'stack' => array('CMS', 'Search research', 'Editorial reviews', 'Analytics', 'Social snippets'),
		'process' => array(
			array('title' => 'Collect the questions', 'text' => 'Start from sales calls, support, and the gaps on the site.'),
			array('title' => 'Choose the form', 'text' => 'A page section, an article, or a short series. Not all three by default.'),
			array('title' => 'Produce with review', 'text' => 'Draft, check the facts with your team, and publish in the CMS.'),
			array('title' => 'Measure use', 'text' => 'Look at the pages, the enquiries, and whether sales actually sends the piece.'),
		),
		'quality' => 'We write in the company’s voice after we have heard it. Claims that need proof stay out until the proof exists. A draft is not public until the person who knows the subject has seen it. If the useful piece is a rewrite of a page the company already has, that comes before a new article.',
		'related' => array('seo', 'social-media-marketing', 'ui-ux-design'),
		'faq' => array(
			array('q' => 'What do content strategy services include?', 'a' => 'The questions worth answering, the page or article that should carry each one, and the writing itself. Search is included when those questions are also the way people arrive.'),
			array('q' => 'Who approves the words?', 'a' => 'You do. We build a review step into the workflow so a subject expert sees the draft before it is public.'),
			array('q' => 'Can you only fix the website copy?', 'a' => 'Yes. A messaging and website-copy engagement does not require a blog program.'),
			$service_faq_common[0],
			$service_faq_common[1],
		),
	),
);
